import type { Question } from "../types";

/* ===== ANGOL NYELVTAN (GRAMMAR) — 3 altéma × 20 kérdés, mindhez exp ===== */
export const ENG_GRAMMAR_TOPIC = {
  id: "eng_grammar",
  title: "Nyelvtan (Grammar)",
  sections: [
    /* ---------- 1) Present Simple ---------- */
    {
      id: "present_simple",
      title: "Egyszerű jelen (Present Simple) – 20 kérdés",
      bank: [
        { q: "He ___ to school every day. (go) (minden nap iskolába jár)", options: ["go", "goes", "going", "gone"], correctIndex: 1, exp: "Present Simple E/3-ban -s: he goes." },
        { q: "They ___ football on Sundays. (play) (vasárnaponként fociznak)", options: ["plays", "playing", "play", "played"], correctIndex: 2, exp: "Többes számban nincs -s: they play." },
        { q: "Does she ___ tea? (like) (szereti a teát?)", options: ["likes", "like", "liking", "liked"], correctIndex: 1, exp: "Kérdésben ‘does’ után alapalak: like." },
        { q: "I ___ TV in the morning. (not/watch) (reggel nem nézek tévét)", options: ["don’t watch", "doesn’t watch", "not watch", "didn’t watch"], correctIndex: 0, exp: "Tagadás I/you/we/they: don’t + V1 → don’t watch." },
        { q: "What time ___ you get up? (mikor kelsz fel?)", options: ["does", "do", "did", "are"], correctIndex: 1, exp: "Kérdés I/you/we/they: do + V1." },
        { q: "My brother ___ German. (not/study) (a bátyám nem tanul németet)", options: ["doesn’t study", "don’t study", "isn’t study", "didn’t study"], correctIndex: 0, exp: "E/3 tagadás: doesn’t + V1 → doesn’t study." },
        { q: "Where ___ they live? (hol laknak?)", options: ["does", "do", "are", "did"], correctIndex: 1, exp: "Kérdő segédige többesben: do." },
        { q: "She always ___ a jacket in winter. (wear) (télen mindig kabátot visel)", options: ["wear", "wears", "is wearing", "wore"], correctIndex: 1, exp: "Szokás → Present Simple; E/3 -s: wears." },
        { q: "Cats ___ milk. (like) (a macskák szeretik a tejet)", options: ["likes", "like", "are liking", "liked"], correctIndex: 1, exp: "Általános igazság; többes alany: like." },
        { q: "___ you speak English? (tudsz angolul?)", options: ["Do", "Are", "Did", "Does"], correctIndex: 0, exp: "Képesség/általános kérdés: Do you…?" },
        { q: "The train ___ at 7. (leave) (a vonat 7-kor indul)", options: ["leave", "leaves", "left", "is leaving"], correctIndex: 1, exp: "Menetrendekhez Present Simple; E/3 -s: leaves." },
        { q: "Water ___ at 100°C. (boil) (a víz 100°C-on forr)", options: ["boils", "boil", "is boiling", "boiled"], correctIndex: 0, exp: "Természeti tény: Present Simple; E/3 -s: boils." },
        { q: "He ___ meat. (not/eat) (nem eszik húst)", options: ["don’t eat", "isn’t eat", "doesn’t eat", "didn’t eat"], correctIndex: 2, exp: "E/3 tagadás: doesn’t + V1 → doesn’t eat." },
        { q: "How often ___ you exercise? (milyen gyakran edzel?)", options: ["are", "do", "does", "did"], correctIndex: 1, exp: "Gyakoriság kérdése: Do you…?" },
        { q: "She usually ___ dinner. (cook) (általában vacsorát főz)", options: ["cook", "cooks", "is cooking", "cooked"], correctIndex: 1, exp: "Szokás → Present Simple E/3: cooks." },
        { q: "We ___ more time. (not/need) (nincs szükségünk több időre)", options: ["don’t need", "doesn’t need", "aren’t need", "didn’t need"], correctIndex: 0, exp: "Tagadás többesben: don’t + V1 → don’t need." },
        { q: "___ they have a car? (van autójuk?)", options: ["Are", "Do", "Did", "Does"], correctIndex: 1, exp: "‘have’ birtoklásnál do/does segédigével: Do they have…?" },
        { q: "My dad ___ in a bank. (work) (apukám egy bankban dolgozik)", options: ["work", "works", "worked", "is working"], correctIndex: 1, exp: "Szokásos tevékenység, E/3 -s: works." },
        { q: "It often ___ in autumn. (rain) (ősszel gyakran esik)", options: ["rains", "rain", "is raining", "rained"], correctIndex: 0, exp: "Gyakoriság → Present Simple; E/3 -s: rains." },
        { q: "Students ___ hard before exams. (study) (a diákok keményen tanulnak vizsgák előtt)", options: ["studies", "study", "are studying", "studied"], correctIndex: 1, exp: "Általános állítás; többes: study." },
      ],
    },

    /* ---------- 2) Past Simple ---------- */
    {
      id: "past_simple",
      title: "Egyszerű múlt (Past Simple) – 20 kérdés",
      bank: [
        { q: "He ___ his grandparents yesterday. (visit) (tegnap meglátogatta a nagyszüleit)", options: ["visit", "visits", "visited", "was visiting"], correctIndex: 2, exp: "‘yesterday’ → Past Simple, reguláris V2: visited." },
        { q: "They ___ to the cinema. (not/go) (nem mentek moziba)", options: ["don’t go", "didn’t go", "weren’t going", "no go"], correctIndex: 1, exp: "Past Simple tagadás: didn’t + V1 → didn’t go." },
        { q: "When ___ you arrive? (mikor érkeztél?)", options: ["do", "did", "was", "were"], correctIndex: 1, exp: "Past Simple kérdés: did + V1 → did you arrive?" },
        { q: "She ___ a new dress last week. (buy) (múlt héten vett egy új ruhát)", options: ["buys", "bought", "buyed", "was buying"], correctIndex: 1, exp: "Past Simple rendhagyó V2: buy → bought." },
        { q: "We ___ at home last night. (be) (tegnap este otthon voltunk)", options: ["was", "were", "are", "be"], correctIndex: 1, exp: "‘we’ múltban: were." },
        { q: "I ___ Tom two days ago. (see) (két napja láttam Tomot)", options: ["see", "saw", "seen", "was seeing"], correctIndex: 1, exp: "Past Simple rendhagyó V2: see → saw." },
        { q: "___ they finish the project? (befejezték a projektet?)", options: ["Do", "Are", "Did", "Were"], correctIndex: 2, exp: "Past Simple kérdés: Did they finish…?" },
        { q: "He ___ the question. (not/understand) (nem értette a kérdést)", options: ["didn’t understand", "doesn’t understand", "wasn’t understand", "not understood"], correctIndex: 0, exp: "Tagadás múltban: didn’t + V1 → didn’t understand." },
        { q: "Where ___ she up? (grow) (hol nőtt fel?)", options: ["does", "did", "was", "has"], correctIndex: 1, exp: "Past Simple kérdés: did + V1 → did she grow up?" },
        { q: "The match ___ at 6. (start) (a meccs 6-kor kezdődött)", options: ["starts", "started", "start", "was starting"], correctIndex: 1, exp: "Past Simple V2 (időpont múltban): started." },
        { q: "I ___ a letter to my friend. (write) (levelet írtam a barátomnak)", options: ["wrote", "write", "written", "was writing"], correctIndex: 0, exp: "Past Simple rendhagyó V2: write → wrote." },
        { q: "She ___ a headache in the morning. (have) (reggel fájt a feje)", options: ["has", "had", "have", "was having"], correctIndex: 1, exp: "Past Simple V2: have → had." },
        { q: "We ___ the bus to school. (take) (busszal mentünk iskolába)", options: ["taked", "took", "take", "taken"], correctIndex: 1, exp: "Past Simple rendhagyó V2: take → took." },
        { q: "He ___ tired after work. (feel) (munka után fáradtnak érezte magát)", options: ["felt", "feeled", "feel", "was feeling"], correctIndex: 0, exp: "Past Simple V2: feel → felt." },
        { q: "___ you find my keys? (megtaláltad a kulcsaimat?)", options: ["Do", "Are", "Did", "Have"], correctIndex: 2, exp: "Past Simple kérdés: Did you find…?" },
        { q: "They ___ late. (come) (későn jöttek)", options: ["comed", "came", "come", "were coming"], correctIndex: 1, exp: "Past Simple V2: come → came." },
        { q: "I ___ the alarm. (not/hear) (nem hallottam az ébresztőt)", options: ["didn’t heard", "didn’t hear", "don’t hear", "wasn’t hearing"], correctIndex: 1, exp: "Tagadás múltban: didn’t + V1 → didn’t hear (nem V2!)." },
        { q: "She ___ her phone on the table. (leave) (az asztalon hagyta a telefonját)", options: ["left", "leaved", "leaves", "was leaving"], correctIndex: 0, exp: "Past Simple V2: leave → left." },
        { q: "We ___ in 2019. (meet) (2019-ben találkoztunk)", options: ["meet", "met", "meeting", "was met"], correctIndex: 1, exp: "Past Simple V2: meet → met." },
        { q: "The teacher ___ us homework. (give) (a tanár házit adott)", options: ["gived", "gave", "gives", "was giving"], correctIndex: 1, exp: "Past Simple V2: give → gave." },
      ],
    },

    /* ---------- 3) Present Perfect ---------- */
    {
      id: "present_perfect",
      title: "Present Perfect – 20 kérdés",
      bank: [
        { q: "I ___ my homework. (just/finish) (épp most fejeztem be a házim)", options: ["just finish", "have just finished", "am just finishing", "has just finished"], correctIndex: 1, exp: "Present Perfect: have + V3; ‘just’ tipikus jelző." },
        { q: "She ___ that film. (never/see) (sosem látta azt a filmet)", options: ["never saw", "has never seen", "have never seen", "never see"], correctIndex: 1, exp: "Present Perfect: has + V3 (she). ‘never’ gyakori jelző." },
        { q: "We ___ here since 2010. (live) (2010 óta itt élünk)", options: ["lived", "have lived", "are living", "was living"], correctIndex: 1, exp: "Időtartam ‘since/for’ → Present Perfect: have lived." },
        { q: "___ you ever ___ to London? (be) (voltál már Londonban?)", options: ["Do / be", "Have / been", "Did / been", "Are / been"], correctIndex: 1, exp: "Kérdés Present Perfectben: Have you been …?" },
        { q: "He ___ the dishes. (already/do) (már elmosogatott)", options: ["already did", "has already done", "have already done", "is already doing"], correctIndex: 1, exp: "Present Perfect: has + done (V3). ‘already’ gyakori jelző." },
        { q: "They ___ yet. (not/decide) (még nem döntöttek)", options: ["haven’t decided", "didn’t decide", "don’t decide", "aren’t deciding"], correctIndex: 0, exp: "Tagadás PP-ben: haven’t + V3; ‘yet’ gyakori." },
        { q: "How long ___ you ___ her? (know) (mióta ismered őt?)", options: ["have / known", "did / know", "do / know", "are / knowing"], correctIndex: 0, exp: "Időtartam (how long) → have + V3: have known." },
        { q: "My phone ___ again. (break) (megint elromlott a telefonom)", options: ["has broken", "broke", "is breaking", "has been breaking"], correctIndex: 0, exp: "Eredmény a jelenben → has broken (PP). ‘broke’ múlt." },
        { q: "The train ___ just ___. (arrive) (a vonat épp most érkezett meg)", options: ["has / arrived", "have / arrived", "is / arriving", "did / arrive"], correctIndex: 0, exp: "‘just’ + PP: has arrived." },
        { q: "I ___ three books this month. (read) (három könyvet elolvastam ebben a hónapban)", options: ["read", "have read", "has read", "am reading"], correctIndex: 1, exp: "Időszak még tart (‘this month’) → have read." },
        { q: "She ___ many emails today. (write) (ma sok e-mailt írt)", options: ["has written", "have written", "wrote", "is writing"], correctIndex: 0, exp: "‘today’ még tart → has written (PP)." },
        { q: "We ___ before. (not/meet) (még nem találkoztunk)", options: ["didn’t meet", "haven’t met", "don’t meet", "aren’t met"], correctIndex: 1, exp: "Tagadás PP-ben: haven’t met." },
        { q: "___ they ___ to the new house? (move) (átköltöztek már az új házba?)", options: ["Did / move", "Have / moved", "Do / move", "Are / moving"], correctIndex: 1, exp: "Kérdés PP-ben: Have they moved…?" },
        { q: "He ___ his keys. (lose) (elvesztette a kulcsait)", options: ["has lost", "lost", "has lose", "is losing"], correctIndex: 0, exp: "Eredmény jelenre hat → has lost (PP)." },
        { q: "I ___ English for five years. (study) (öt éve tanulok angolul)", options: ["studied", "have studied", "am studying", "had studied"], correctIndex: 1, exp: "Tartam: for five years → have studied (PP)." },
        { q: "She ___ her project yet. (not/finish) (még nem fejezte be a projektjét)", options: ["hasn’t finished", "didn’t finish", "doesn’t finish", "isn’t finishing"], correctIndex: 0, exp: "‘yet’ + PP tagadás: hasn’t finished." },
        { q: "___ you ___ your homework? (do) (megcsináltad a házidat?)", options: ["Do / do", "Are / doing", "Have / done", "Did / done"], correctIndex: 2, exp: "Kérdés PP-ben: Have you done…?" },
        { q: "The rain ___. (stop) (elállt az eső)", options: ["has stopped", "stopped", "is stopping", "has stop"], correctIndex: 0, exp: "Jelenre ható eredmény → has stopped (PP)." },
        { q: "I ___ Paris twice. (visit) (kétszer jártam Párizsban)", options: ["visited", "have visited", "has visited", "am visiting"], correctIndex: 1, exp: "Élettapasztalat → Present Perfect: have visited." },
        { q: "They ___ a new job recently. (start) (nemrég új munkát kezdtek)", options: ["have started", "started", "has started", "are starting"], correctIndex: 0, exp: "‘recently’ gyakori PP-jelző → have started." },
      ],
    },
  ],
};
/* ===== ANGOL SZÓKINCS (VOCABULARY) — 3 altéma × 20 kérdés, exp magyarázattal ===== */
export const ENG_VOCAB_TOPIC = {
  id: "eng_vocabulary",
  title: "Szókincs (Vocabulary)",
  sections: [
    /* ---------- 1) Mindennapok (Everyday) ---------- */
    {
      id: "everyday",
      title: "Mindennapok (Everyday) – 20 kérdés",
      bank: [
        { q: "I usually have ___ at 7 a.m. (reggeli)", options: ["breakfast", "lunch", "dinner", "snack"], correctIndex: 0, exp: "Reggeli → breakfast, lunch = ebéd, dinner = vacsora." },
        { q: "She goes to the ___ three times a week. (edzőterem)", options: ["cinema", "gym", "library", "park"], correctIndex: 1, exp: "‘go to the gym’ = edzőterembe jár." },
        { q: "Please ___ the window, it’s hot here. (nyisd ki)", options: ["close", "open", "fix", "cover"], correctIndex: 1, exp: "‘open the window’ = kinyitni az ablakot." },
        { q: "I need to ___ my room today. (kitakarítani)", options: ["cook", "paint", "clean", "wash"], correctIndex: 2, exp: "Takarítani = clean a room." },
        { q: "He ___ a shower every morning. (zuhanyozik)", options: ["takes", "does", "makes", "has"], correctIndex: 0, exp: "‘take a shower’ → zuhanyozik. Nem ‘do’ vagy ‘make’." },
        { q: "Don’t forget to ___ your teeth. (fogmosás)", options: ["comb", "wash", "brush", "polish"], correctIndex: 2, exp: "‘brush your teeth’ = fogat mos." },
        { q: "We often ___ TV after dinner. (tévét nézünk)", options: ["read", "watch", "look", "see"], correctIndex: 1, exp: "TV-t nézni = watch TV." },
        { q: "She ___ home at 7 p.m. (hazaér)", options: ["goes", "arrives", "comes", "leaves"], correctIndex: 2, exp: "‘come home’ = hazaérkezik." },
        { q: "I ___ to music on the bus. (zenét hallgatok)", options: ["hear", "listen", "play", "sound"], correctIndex: 1, exp: "‘listen to music’ – mindig ‘to’ előljáróval." },
        { q: "He is ___ the dishes now. (mosogat)", options: ["doing", "making", "washing", "cleaning"], correctIndex: 0, exp: "‘do the dishes’ = elmosogat." },
        { q: "Could you ___ me, please? (segíteni)", options: ["help", "hold", "keep", "give"], correctIndex: 0, exp: "‘help me’ = segíts nekem." },
        { q: "My mother is a great ___. (szakács)", options: ["waiter", "teacher", "cook", "driver"], correctIndex: 2, exp: "‘cook’ = szakács. ‘cooking’ = főzés." },
        { q: "Take the ___ to the third floor. (lift)", options: ["stairs", "elevator", "escalator", "ladder"], correctIndex: 1, exp: "‘take the elevator/lift’ = használd a liftet." },
        { q: "I’m ___, can I have some water? (szomjas)", options: ["hungry", "sleepy", "thirsty", "tired"], correctIndex: 2, exp: "‘thirsty’ = szomjas. ‘hungry’ = éhes." },
        { q: "Turn ___ the lights, please. (kapcsold le)", options: ["on", "up", "out", "off"], correctIndex: 3, exp: "‘turn off’ = lekapcsolni, ‘turn on’ = felkapcsolni." },
        { q: "We usually ___ at noon. (ebédelünk)", options: ["break", "dine", "lunch", "have lunch"], correctIndex: 3, exp: "‘have lunch’ = ebédelni." },
        { q: "He often ___ the dog in the park. (sétáltatja)", options: ["walks", "runs", "drives", "takes"], correctIndex: 0, exp: "‘walk the dog’ = megsétáltatni a kutyát." },
        { q: "I need to buy ___ at the supermarket. (élelmiszer)", options: ["medicine", "groceries", "tools", "clothes"], correctIndex: 1, exp: "‘groceries’ = élelmiszer." },
        { q: "She always wears a ___ in winter. (sál)", options: ["glove", "belt", "scarf", "cap"], correctIndex: 2, exp: "‘scarf’ = sál, ‘cap’ = sapka." },
        { q: "Let’s ___ a photo! (készítsünk)", options: ["make", "do", "take", "get"], correctIndex: 2, exp: "‘take a photo’ = fényképet készíteni." },
      ],
    },

    /* ---------- 2) Iskola (School) ---------- */
    {
      id: "school",
      title: "Iskola (School) – 20 kérdés",
      bank: [
        { q: "We have a math ___ today. (dolgozat)", options: ["homework", "test", "project", "lesson"], correctIndex: 1, exp: "‘test’ = dolgozat." },
        { q: "Please open your ___. (tankönyv)", options: ["copybooks", "textbooks", "notebooks", "handbooks"], correctIndex: 1, exp: "‘textbook’ = tankönyv." },
        { q: "The first ___ starts at 8 a.m. (tanóra)", options: ["break", "class", "course", "club"], correctIndex: 1, exp: "‘class starts’ = óra kezdődik." },
        { q: "We write with a ___. (ceruza)", options: ["pen", "pencil", "marker", "chalk"], correctIndex: 1, exp: "‘pencil’ = ceruza." },
        { q: "The teacher writes on the ___. (tábla)", options: ["screen", "board", "wall", "paper"], correctIndex: 1, exp: "‘blackboard/board’ = tábla." },
        { q: "Don’t be late for ___. (iskola)", options: ["work", "school", "course", "lesson"], correctIndex: 1, exp: "‘late for school’ = elkésni az iskolából." },
        { q: "We have a ___ after two classes. (szünet)", options: ["holiday", "vacation", "break", "trip"], correctIndex: 2, exp: "‘break’ = szünet az órák között." },
        { q: "We study in the school ___. (könyvtár)", options: ["canteen", "gym", "library", "lab"], correctIndex: 2, exp: "‘library’ = könyvtár." },
        { q: "Please ___ your homework. (leadni)", options: ["hand out", "hand in", "take in", "bring in"], correctIndex: 1, exp: "‘hand in’ = beadni (feladatot)." },
        { q: "There are thirty ___ in my class. (diák)", options: ["pupils", "teachers", "workers", "parents"], correctIndex: 0, exp: "‘pupil/student’ = diák." },
        { q: "We have ___ on Monday: PE, English, Biology. (tantárgyak)", options: ["subjects", "themes", "topics", "titles"], correctIndex: 0, exp: "‘subject’ = tantárgy." },
        { q: "I got a good ___ in history. (jegy)", options: ["mark", "sign", "note", "gradebook"], correctIndex: 0, exp: "‘get a good mark’ = jó jegyet kapni." },
        { q: "Don’t ___ during the test. (puskázni)", options: ["copy", "cheat", "discuss", "share"], correctIndex: 1, exp: "‘cheat’ = csalni, puskázni." },
        { q: "We did an experiment in the ___. (labor)", options: ["canteen", "lab", "office", "hall"], correctIndex: 1, exp: "‘lab’ = laboratórium." },
        { q: "The school ___ starts in September. (tanév)", options: ["year", "term", "semester", "school year"], correctIndex: 3, exp: "‘school year’ = tanév." },
        { q: "Our English ___ is very kind. (tanár)", options: ["pupil", "teacher", "headmaster", "trainer"], correctIndex: 1, exp: "‘teacher’ = tanár." },
        { q: "I need a new ___ for notes. (füzet)", options: ["folder", "file", "notebook", "sheet"], correctIndex: 2, exp: "‘notebook’ = füzet." },
        { q: "Please ___ the text quietly. (olvasd)", options: ["write", "read", "listen", "speak"], correctIndex: 1, exp: "‘read the text’ = olvasd el a szöveget." },
        { q: "We did our homework on the ___. (számítógép)", options: ["computer", "phone", "tablet", "TV"], correctIndex: 0, exp: "‘on the computer’ – eszköznél ‘on’." },
        { q: "The headmaster works in the ___. (igazgatói iroda)", options: ["office", "staff room", "reception", "hall"], correctIndex: 0, exp: "‘headmaster’s office’ = igazgatói iroda." },
      ],
    },

    /* ---------- 3) Utazás (Travel) ---------- */
    {
      id: "travel",
      title: "Utazás (Travel) – 20 kérdés",
      bank: [
        { q: "We’re going to the airport to catch our ___. (repülőjárat)", options: ["flight", "train", "ship", "bus"], correctIndex: 0, exp: "‘catch a flight’ = elérni a járatot." },
        { q: "Please show me your ___. (útlevél)", options: ["ticket", "passport", "boarding pass", "ID card"], correctIndex: 1, exp: "‘passport’ = útlevél." },
        { q: "We need to ___ a room for two nights. (szobát foglalni)", options: ["rent", "book", "buy", "order"], correctIndex: 1, exp: "‘book a room’ = szobát foglalni." },
        { q: "The train ___ at platform 3. (indul)", options: ["arrives", "leaves", "stops", "comes"], correctIndex: 1, exp: "‘leave’ = indul (vonat, busz)." },
        { q: "We travelled by ___. (metró)", options: ["tram", "underground", "coach", "taxi"], correctIndex: 1, exp: "‘underground’ vagy ‘subway’ = metró." },
        { q: "Let’s check the bus ___. (menetrend)", options: ["plan", "schedule", "map", "route"], correctIndex: 1, exp: "‘schedule’ = menetrend, beosztás." },
        { q: "Where is the hotel ___? (recepció)", options: ["kitchen", "reception", "balcony", "entrance"], correctIndex: 1, exp: "‘reception’ = recepció." },
        { q: "We need a single and a ___ room. (kétágyas)", options: ["double", "couple", "twin", "two"], correctIndex: 0, exp: "‘double room’ = kétágyas szoba." },
        { q: "How much is the ___ ticket? (retúrjegy)", options: ["one-way", "return", "year", "group"], correctIndex: 1, exp: "‘return ticket’ = retúrjegy." },
        { q: "Can I pay by ___? (bankkártya)", options: ["cash", "change", "card", "cheque"], correctIndex: 2, exp: "‘pay by card’ = kártyával fizetni." },
        { q: "We went ___ in the old town. (városnézés)", options: ["hiking", "sightseeing", "camping", "shopping"], correctIndex: 1, exp: "‘go sightseeing’ = várost nézni." },
        { q: "The luggage is too ___. (nehéz)", options: ["light", "heavy", "cheap", "late"], correctIndex: 1, exp: "‘heavy luggage’ = nehéz csomag." },
        { q: "Our room has a beautiful ___. (kilátás)", options: ["view", "scene", "picture", "look"], correctIndex: 0, exp: "‘have a view’ = kilátása van." },
        { q: "We bought some ___ for our friends. (ajándéktárgyak)", options: ["ingredients", "souvenirs", "tools", "materials"], correctIndex: 1, exp: "‘souvenirs’ = ajándéktárgyak." },
        { q: "The bus was ___. (zsúfolt)", options: ["empty", "crowded", "quiet", "fast"], correctIndex: 1, exp: "‘crowded’ = zsúfolt." },
        { q: "Where can I ___ a taxi? (fogni / hívni)", options: ["take", "catch", "call", "rent"], correctIndex: 2, exp: "‘call a taxi’ = taxit hívni." },
        { q: "The flight was two hours ___. (késés)", options: ["late", "delay", "delayed", "slow"], correctIndex: 2, exp: "‘delayed’ = késik, késleltetett." },
        { q: "We need to ___ through security. (átmenni)", options: ["pass", "cross", "walk", "go"], correctIndex: 0, exp: "‘pass through’ = átmenni (ellenőrzésen)." },
        { q: "I’d like a room with ___. (reggeli)", options: ["dinner", "half board", "full board", "breakfast"], correctIndex: 3, exp: "‘room with breakfast’ = reggelivel." },
        { q: "What time is the hotel ___? (kijelentkezés)", options: ["check-out", "check-in", "start", "opening"], correctIndex: 0, exp: "‘check-out’ = kijelentkezés." },
      ],
    },
  ],
};
/* ===== ANGOL – RENDHAGYÓ IGÉK (IRREGULAR VERBS) — exp-ekkel ===== */
export const ENG_IRREG_TOPIC = {
  id: "eng_irregulars",
  title: "Rendhagyó igék (Irregular Verbs)",
  sections: [
    /* ---------- 1) Táblázat (magyar → 3 alak) ---------- */
    {
      id: "irreg_all",
      title: "Rendhagyó igék – táblázat (20 kérdés)",
      bank: [
        {
          q: "lenni (létige) – válaszd a helyes hármast!",
          options: ["be – was/were – been", "be – were/was – beed", "be – is/are – been", "be – was – be"],
          correctIndex: 0,
          exp: "A ‘be’ múltja: was/were, V3: been. A ‘beed’ nem létezik; ‘is/are’ jelen idejű alakok.",
        },
        {
          q: "menni – válaszd a helyes hármast!",
          options: ["go – went – gone", "go – goed – gone", "go – went – went", "go – gone – went"],
          correctIndex: 0,
          exp: "go → went (V2), gone (V3). A ‘goed’ hibás; V3 nem ‘went’.",
        },
        {
          q: "jönni – válaszd a helyes hármast!",
          options: ["come – came – come", "come – comed – come", "come – came – came", "come – come – came"],
          correctIndex: 0,
          exp: "come → came (V2), come (V3). A ‘comed’ hibás; V3 sem ‘came’.",
        },
        {
          q: "látni – válaszd a helyes hármast!",
          options: ["see – saw – seen", "see – seed – seen", "see – saw – saw", "see – seen – saw"],
          correctIndex: 0,
          exp: "see → saw (V2), seen (V3). A ‘seed’ hibás; V2≠V3.",
        },
        {
          q: "venni (kézbe/utazni) – válaszd a helyes hármast!",
          options: ["take – took – taken", "take – taken – took", "take – taked – taken", "take – took – took"],
          correctIndex: 0,
          exp: "take → took (V2), taken (V3). A ‘taked’ szabálytalan; V3 nem ‘took’.",
        },
        {
          q: "adni – válaszd a helyes hármast!",
          options: ["give – gave – given", "give – given – gave", "give – gaved – given", "give – gave – gave"],
          correctIndex: 0,
          exp: "give → gave (V2), given (V3). A ‘gaved’ nem helyes; V3 nem ‘gave’.",
        },
        {
          q: "kapni – válaszd a helyes hármast!",
          options: ["get – got – got/gotten", "get – get – got", "get – got – get", "get – gotten – got"],
          correctIndex: 0,
          exp: "get → got (V2), got/gotten (V3, AmE: gotten). A többi alakpár hibás sorrend.",
        },
        {
          q: "csinálni/készíteni (make) – válaszd a helyes hármast!",
          options: ["make – made – made", "make – maked – made", "make – made – maked", "make – made – maden"],
          correctIndex: 0,
          exp: "make → made (V2/V3). A ‘maked/maden’ nem létezik.",
        },
        {
          q: "csinálni (do) – válaszd a helyes hármast!",
          options: ["do – did – done", "do – done – did", "do – did – did", "do – do – done"],
          correctIndex: 0,
          exp: "do → did (V2), done (V3). A V2 és V3 nem cserélhető fel.",
        },
        {
          q: "birtokolni – válaszd a helyes hármast!",
          options: ["have – had – had", "have – has – had", "have – haved – had", "have – had – has"],
          correctIndex: 0,
          exp: "have → had (V2/V3). ‘has’ jelen egyes 3.; ‘haved’ hibás.",
        },
        {
          q: "mondani – válaszd a helyes hármast!",
          options: ["say – said – said", "say – said – sayed", "say – sayed – said", "say – said – says"],
          correctIndex: 0,
          exp: "say → said (V2/V3). ‘sayed’ nincs; ‘says’ jelen E/3.",
        },
        {
          q: "találni – válaszd a helyes hármast!",
          options: ["find – found – found", "find – finded – found", "find – found – founded", "find – found – finds"],
          correctIndex: 0,
          exp: "find → found (V2/V3). ‘finded’ hibás; ‘founded’ más igéhez tartozik.",
        },
        {
          q: "gondolni – válaszd a helyes hármast!",
          options: ["think – thought – thought", "think – thinked – thought", "think – thought – thinked", "think – think – thought"],
          correctIndex: 0,
          exp: "think → thought (V2/V3). ‘thinked’ nem létezik.",
        },
        {
          q: "tudni/ismerni – válaszd a helyes hármast!",
          options: ["know – knew – known", "know – known – knew", "know – knowed – known", "know – knew – know"],
          correctIndex: 0,
          exp: "know → knew (V2), known (V3). ‘knowed’ hibás; V3 nem ‘knew’.",
        },
        {
          q: "írni – válaszd a helyes hármast!",
          options: ["write – wrote – written", "write – written – wrote", "write – wroted – written", "write – wrote – writed"],
          correctIndex: 0,
          exp: "write → wrote (V2), written (V3). ‘wroted/writed’ hibás.",
        },
        {
          q: "olvasni – válaszd a helyes hármast!",
          options: ["read – read – read (ejtsd: /red/)", "read – read – read (ejtsd: /riːd/ minden alakban)", "read – rode – read", "read – readed – read"],
          correctIndex: 0,
          exp: "Írás ugyanaz, kiejtés múltban/V3-ban /red/. A ‘rode/readed’ hibás.",
        },
        {
          q: "beszélni – válaszd a helyes hármast!",
          options: ["speak – spoke – spoken", "speak – spoken – spoke", "speak – spoked – spoken", "speak – spoke – spoked"],
          correctIndex: 0,
          exp: "speak → spoke (V2), spoken (V3). ‘spoked’ hibás.",
        },
        {
          q: "enni – válaszd a helyes hármast!",
          options: ["eat – ate – eaten", "eat – eaten – ate", "eat – eated – eaten", "eat – ate – ate"],
          correctIndex: 0,
          exp: "eat → ate (V2), eaten (V3). ‘eated’ nincs; V2≠V3.",
        },
        {
          q: "inni – válaszd a helyes hármast!",
          options: ["drink – drank – drunk", "drink – drunk – drank", "drink – drinked – drunk", "drink – drank – drinked"],
          correctIndex: 0,
          exp: "drink → drank (V2), drunk (V3). ‘drinked’ hibás.",
        },
        {
          q: "venni (vásárolni) – válaszd a helyes hármast!",
          options: ["buy – bought – bought", "buy – buyed – bought", "buy – bought – buyed", "buy – bought – buys"],
          correctIndex: 0,
          exp: "buy → bought (V2/V3). ‘buyed’ hibás; ‘buys’ jelen E/3.",
        },
      ],
    },

    /* ---------- 2) Alkalmazás (mondatba illesztés, magyarázattal) ---------- */
    {
      id: "irreg_usage",
      title: "Rendhagyó igék – alkalmazás (20 kérdés)",
      bank: [
        {
          q: "He ___ to school yesterday. (go) (tegnap iskolába ment)",
          options: ["goes", "went", "gone", "was going"],
          correctIndex: 1,
          exp: "Egyszerű múlt → ‘yesterday’; go V2 = went. A ‘gone’ V3, ‘was going’ folyamatos múlt.",
        },
        {
          q: "I have ___ breakfast already. (eat) (már megreggeliztem)",
          options: ["ate", "eaten", "eated", "eating"],
          correctIndex: 1,
          exp: "Present Perfect: have + V3 → eaten. ‘ate’ V2; ‘eated’ hibás.",
        },
        {
          q: "She ___ a letter last night. (write) (tegnap este levelet írt)",
          options: ["wrote", "written", "write", "was written"],
          correctIndex: 0,
          exp: "Egyszerű múlt: write V2 = wrote. ‘written’ V3 (nem aktív igealak).",
        },
        {
          q: "We have ___ in this city since 2015. (live) (2015 óta élünk itt)",
          options: ["lived", "live", "living", "lives"],
          correctIndex: 0,
          exp: "‘since’ → tartam, Present Perfect: have + lived.",
        },
        {
          q: "They ___ the bus, so they were late. (miss) (lekésték a buszt)",
          options: ["miss", "missed", "have missed", "were missing"],
          correctIndex: 1,
          exp: "Egyszerű múlt, múltbeli ok-okozat → missed.",
        },
        {
          q: "Have you ever ___ to London? (be) (voltál már Londonban?)",
          options: ["been", "was", "were", "be"],
          correctIndex: 0,
          exp: "Present Perfect kérdés: have + been (be V3).",
        },
        {
          q: "He ___ his keys yesterday. (lose) (tegnap elvesztette a kulcsait)",
          options: ["lose", "lost", "has lost", "loses"],
          correctIndex: 1,
          exp: "Egyszerű múlt: lose V2 = lost. ‘has lost’ jelenhez kapcsol.",
        },
        {
          q: "I have never ___ that movie. (see) (sosem láttam azt a filmet)",
          options: ["saw", "seen", "see", "seeing"],
          correctIndex: 1,
          exp: "Present Perfect: have + seen (V3). ‘saw’ V2.",
        },
        {
          q: "She ___ a great cake for my birthday. (make) (szuper tortát készített a szülinapomra)",
          options: ["made", "make", "has make", "maked"],
          correctIndex: 0,
          exp: "Egyszerű múlt: make V2 = made. ‘maked’ hibás.",
        },
        {
          q: "The train has just ___. (arrive) (a vonat épp most érkezett meg)",
          options: ["arrived", "arrive", "arriving", "arrives"],
          correctIndex: 0,
          exp: "‘just’ → Present Perfect: has arrived.",
        },
        {
          q: "We ___ a new car last month. (buy) (múlt hónapban vettünk egy új autót)",
          options: ["buy", "bought", "have bought", "buyed"],
          correctIndex: 1,
          exp: "Egyszerű múlt: buy V2 = bought. ‘buyed’ hibás.",
        },
        {
          q: "He ___ me a book two days ago. (give) (két napja adott egy könyvet)",
          options: ["gave", "given", "gived", "gives"],
          correctIndex: 0,
          exp: "Egyszerű múlt: give V2 = gave. ‘given’ V3.",
        },
        {
          q: "I have ___ my homework. (do) (kész a házim)",
          options: ["did", "done", "doing", "does"],
          correctIndex: 1,
          exp: "Present Perfect: have + done (do V3).",
        },
        {
          q: "They ___ a lot of photos on their trip. (take) (sok fotót készítettek az útjukon)",
          options: ["took", "taken", "take", "have take"],
          correctIndex: 0,
          exp: "Egyszerű múlt: take V2 = took. ‘taken’ V3.",
        },
        {
          q: "She ___ a beautiful song at the concert. (sing) (gyönyörű dalt énekelt a koncerten)",
          options: ["sang", "sung", "singed", "sing"],
          correctIndex: 0,
          exp: "Egyszerű múlt: sing V2 = sang. ‘sung’ V3.",
        },
        {
          q: "We have ___ the museum many times. (visit) (sokszor meglátogattuk a múzeumot)",
          options: ["visited", "visit", "visiting", "visits"],
          correctIndex: 0,
          exp: "Present Perfect: have + visited (rendes V3).",
        },
        {
          q: "He ___ very tired after work yesterday. (feel) (tegnap munka után nagyon fáradt volt)",
          options: ["felt", "feels", "has felt", "feeling"],
          correctIndex: 0,
          exp: "Egyszerű múlt: feel V2 = felt.",
        },
        {
          q: "I have ___ the book you gave me. (read) (elolvastam a könyvet, amit adtál)",
          options: ["read (/red/)", "read (/riːd/)", "rode", "readed"],
          correctIndex: 0,
          exp: "Present Perfect: have + read (kiejtés /red/). ‘readed’ hibás.",
        },
        {
          q: "She ___ to me carefully during the meeting. (speak) (figyelmesen beszélt hozzám a megbeszélésen)",
          options: ["spoke", "spoken", "speaked", "speaks"],
          correctIndex: 0,
          exp: "Egyszerű múlt: speak V2 = spoke. ‘spoken’ V3.",
        },
        {
          q: "They have ___ a new friend online. (find) (új barátot találtak online)",
          options: ["found", "finded", "find", "founded"],
          correctIndex: 0,
          exp: "Present Perfect: have + found (find V3). ‘finded’ hibás.",
        },
      ],
    },
  ],
};
/* ===== ANGOL – SZÖVEGÉRTÉS (READING) — 1 altéma × 20 kérdés, exp-ekkel ===== */
export const ENG_READING_TOPIC = {
  id: "eng_reading",
  title: "Szövegértés (Reading)",
  sections: [
    {
      id: "short_texts",
      title: "Rövid szövegek – megértés (20 kérdés)",
      bank: [
        {
          q: "Tom gets up at 6:30, catches the 7 o’clock bus, and starts school at 8. What time does Tom’s school start? (HU: Tom 6:30-kor kel, 7-es busszal megy, 8-kor kezdődik a suli. Mikor kezdődik az iskola?)",
          options: ["6:30", "7:00", "7:30", "8:00"],
          correctIndex: 3,
          exp: "A szöveg egyértelműen: „starts school at 8” → 8:00.",
        },
        {
          q: "The museum is closed on Mondays but open from Tuesday to Sunday. Which day can you NOT visit? (HU: A múzeum hétfőn zárva, kedd–vasárnap nyitva. Melyik napon nem látogatható?)",
          options: ["Saturday", "Monday", "Sunday", "Tuesday"],
          correctIndex: 1,
          exp: "‘closed on Mondays’ → hétfőn nem látogatható.",
        },
        {
          q: "Emma’s favorite subjects are English and Art, but she dislikes Math. Which subject does Emma NOT like? (HU: Emma kedvencei: angol és rajz, de a matekot nem szereti. Melyiket nem szereti?)",
          options: ["Art", "English", "Math", "History"],
          correctIndex: 2,
          exp: "A szöveg: ‘she dislikes Math’.",
        },
        {
          q: "The café offers free Wi-Fi and student discounts after 5 p.m. What is free at the café? (HU: A kávézó ingyen Wi-Fit és diák kedvezményt ad 17 óra után. Mi ingyenes?)",
          options: ["Drinks", "Wi-Fi", "Snacks", "Nothing"],
          correctIndex: 1,
          exp: "‘offers free Wi-Fi’ → a Wi-Fi ingyenes.",
        },
        {
          q: "Liam usually walks to school, but when it rains, he takes the tram. How does he go to school on rainy days? (HU: Liam általában gyalog megy, esőben villamossal. Esős napon mivel megy?)",
          options: ["By bus", "On foot", "By tram", "By car"],
          correctIndex: 2,
          exp: "‘when it rains, he takes the tram’.",
        },
        {
          q: "There is a sign: “Library: Silence, please.” What does the sign ask you to do? (HU: Tábla: „Könyvtár: Csend, kérem.” Mit kér a tábla?)",
          options: ["Speak loudly", "Be quiet", "Use phones", "Eat snacks"],
          correctIndex: 1,
          exp: "A „Silence, please” azt jelenti: maradj csendben.",
        },
        {
          q: "The weather forecast says: ‘Cloudy in the morning, sunny in the afternoon.’ What will the afternoon be like? (HU: Időjárás: délelőtt felhős, délután napos. Milyen lesz a délután?)",
          options: ["Rainy", "Snowy", "Sunny", "Windy"],
          correctIndex: 2,
          exp: "‘sunny in the afternoon’ → napos.",
        },
        {
          q: "Anna can’t meet at 3 p.m. because she has a dentist appointment then. Why can’t Anna meet at 3 p.m.? (HU: Anna 15:00-kor nem ér rá, fogorvoshoz megy. Miért nem?)",
          options: ["She is at school", "She is traveling", "She has a dentist appointment", "She is sick"],
          correctIndex: 2,
          exp: "A szöveg kifejezetten ezt mondja.",
        },
        {
          q: "“No entry” is written on the door. What does it mean? (HU: Az ajtón „Belépni tilos”. Mit jelent?)",
          options: ["You can enter", "Do not enter", "Knock first", "Staff only, but you can try"],
          correctIndex: 1,
          exp: "‘No entry’ = belépni tilos.",
        },
        {
          q: "The sports club opens at 9 a.m. and closes at 8 p.m. How many hours is it open? (HU: A sportklub 9–20 óráig tart nyitva. Hány órát?)",
          options: ["9 hours", "10 hours", "11 hours", "12 hours"],
          correctIndex: 2,
          exp: "9→20 = 11 óra.",
        },
        {
          q: "Mia drinks tea every morning and coffee only on weekends. What does she drink every morning? (HU: Mia minden reggel teát iszik, kávét csak hétvégén. Mit iszik reggelente?)",
          options: ["Coffee", "Tea", "Juice", "Milk"],
          correctIndex: 1,
          exp: "‘drinks tea every morning’.",
        },
        {
          q: "The sign says: “Please keep off the grass.” What should people do? (HU: Tábla: „Kérjük, ne lépjen a fűre.” Mit tegyenek az emberek?)",
          options: ["Walk on the grass", "Sit on the grass", "Avoid the grass", "Water the grass"],
          correctIndex: 2,
          exp: "‘keep off the grass’ = ne menj a fűre.",
        },
        {
          q: "Jack’s train leaves at 6:45. He arrives at the station at 6:50. What will probably happen? (HU: A vonat 6:45-kor indul, Jack 6:50-re ér oda. Mi történik valószínűleg?)",
          options: ["He will miss the train", "He will catch the train", "The train will wait", "He will be early"],
          correctIndex: 0,
          exp: "Később érkezik, mint az indulás → lekési.",
        },
        {
          q: "On the menu: ‘Soup of the day – tomato’. What soup is offered today? (HU: Napi leves: paradicsom. Milyen levest kínálnak ma?)",
          options: ["Chicken soup", "Tomato soup", "Vegetable soup", "Mushroom soup"],
          correctIndex: 1,
          exp: "‘tomato’ → paradicsomleves.",
        },
        {
          q: "The email says: “Meeting moved from Tuesday to Thursday.” When is the meeting now? (HU: Az e-mail: a meeting kedd helyett csütörtök. Mikor lesz most?)",
          options: ["Monday", "Tuesday", "Wednesday", "Thursday"],
          correctIndex: 3,
          exp: "‘moved … to Thursday’.",
        },
        {
          q: "The poster: “School trip: bring a bottle of water and a hat.” What should students bring? (HU: Plakát: osztálykirándulás – hozz vizet és sapkát. Mit hozzanak?)",
          options: ["Water and a hat", "Snacks only", "Money only", "Nothing"],
          correctIndex: 0,
          exp: "Két dolog: víz és sapka.",
        },
        {
          q: "Lucy reads before bed because it helps her relax. Why does Lucy read before bed? (HU: Lucy lefekvés előtt olvas, mert ellazítja. Miért olvas?)",
          options: ["To study", "To relax", "To stay awake", "To finish homework"],
          correctIndex: 1,
          exp: "‘because it helps her relax’.",
        },
        {
          q: "The weather app shows: 3°C, strong wind, and snow. What should you probably wear? (HU: 3°C, erős szél, hó. Mit érdemes felvenni?)",
          options: ["T-shirt and shorts", "Light jacket", "Warm coat and hat", "Sandals"],
          correctIndex: 2,
          exp: "Hideg és szeles → meleg kabát + sapka.",
        },
        {
          q: "“Exit” signs point to the left. Which way should you go to leave the building? (HU: A „Kijárat” táblák balra mutatnak. Merre menj a kijárathoz?)",
          options: ["Right", "Left", "Upstairs", "Downstairs"],
          correctIndex: 1,
          exp: "A jelzés balra mutat → balra menj.",
        },
        {
          q: "The instruction: “Charge the phone before the trip.” What should you do? (HU: Utasítás: Töltsd fel a telefont az utazás előtt. Mit tegyél?)",
          options: ["Turn off the phone", "Buy a new phone", "Charge the phone", "Install new apps"],
          correctIndex: 2,
          exp: "‘Charge the phone’ = töltsd fel a telefont.",
        },
      ],
    },
  ],
};

/* --- Ha külön gyűjtöd, tedd be a TOPIC_TREE-be is: --- */
export const TOPIC_TREE = [
ENG_GRAMMAR_TOPIC,
ENG_VOCAB_TOPIC,
ENG_IRREG_TOPIC,
ENG_READING_TOPIC,
];
