// lib/nemet/bank.ts

/* ===== Típusok ===== */
export type Question = {
  q: string;
  a: string | string[];   // helyes válasz (egy vagy több)
  options?: string[];      // válaszlehetőségek
};

export type Section = {
  id: string;
  title: string;
  color?: string;
  questions?: Question[];
};

export type Topic = {
  id: string;
  title: string;
  sections: Section[];
};

/* ===== TOPIC TREE ===== */
export const TOPIC_TREE: Topic[] = [
  /* ========== 1) Német alapok ========== */
  {
    id: "nemet_alapok",
    title: "Német alapok",
    sections: [
      {
        id: "abc_kiejtes",
        title: "ABC és kiejtés",
        color: "#38bdf8",
        questions: [
          { q: "Hány betűből áll a német ábécé?", a: ["26"], options: ["24", "25", "26", "27"] },
          { q: "Mi a ß betű neve németül?", a: ["Eszett"], options: ["Doppel-S", "Schnee", "Eszett", "Ess"] },
          { q: "Melyik szó tartalmaz umlautot?", a: ["Mädchen"], options: ["Mann", "Haus", "Mädchen", "Tag"] },
          { q: "Melyik szóban ejtik a 'ch'-t [ɪç]-ként?", a: ["ich"], options: ["Bach", "ich", "Milch", "Lach"] },
          { q: "Melyik betű ejtése 'faú'?", a: ["v"], options: ["w", "v", "f", "u"] },
          { q: "Hogyan ejtjük a 'j'-t németül?", a: ["j mint 'j'"], options: ["dzs", "j", "z", "gy"] },
          { q: "Mi az 'ä' kiejtése legközelebb?", a: ["e"], options: ["a", "e", "ö", "ü"] },
          { q: "Melyik szóban van hosszú 'ie' hang?", a: ["Tiere"], options: ["Tiere", "mit", "bitte", "finden"] },
          { q: "Mi a 'u' umlautos formája?", a: ["ü"], options: ["ö", "ä", "ü", "û"] },
          { q: "Melyik szó tartalmaz 'ß'-t?", a: ["Straße"], options: ["Wasser", "Straße", "Tasse", "Gross"] },
          { q: "A 'ch' [ax] hangja melyik szóban hallható?", a: ["Bach"], options: ["ich", "Milch", "Bach", "Licht"] },
          { q: "Mi az 'ö' kiejtése hasonlít?", a: ["ö mint francia 'eu'"], options: ["a", "é", "ö", "o"] },
          { q: "A 'w' németül hogyan ejtendő?", a: ["v"], options: ["v", "w", "b", "f"] },
          { q: "Melyik szóban rövid az 'u' hang?", a: ["Hund"], options: ["Uhr", "Blume", "Hund", "Schule"] },
          { q: "Mi a német ábécé első betűje?", a: ["A"], options: ["A", "B", "C", "D"] },
          { q: "Melyik betű követi az 'H'-t?", a: ["I"], options: ["G", "I", "J", "K"] },
          { q: "Mit jelent a 'Buchstabe' szó?", a: ["betű"], options: ["szó", "betű", "mondat", "név"] },
          { q: "Mi a 'Vogel' első betűjének ejtése?", a: ["faú"], options: ["vé", "faú", "eff", "bé"] },
          { q: "Melyik szó tartalmaz két magánhangzót egymás után?", a: ["Mai"], options: ["Mai", "Tag", "Hund", "Ball"] },
          { q: "Mi a 'z' kiejtése németül?", a: ["c"], options: ["z", "c", "dz", "sz"] },
        ],
      },
      {
        id: "koszones_bemutatkozas",
        title: "Köszönés, bemutatkozás",
        color: "#60a5fa",
        questions: [
          { q: "Mit jelent: 'Guten Tag'?", a: ["Jó napot!"], options: ["Jó estét!", "Jó napot!", "Jó reggelt!", "Viszlát!"] },
          { q: "Mit mondasz, ha reggel találkozol valakivel?", a: ["Guten Morgen!"], options: ["Guten Abend!", "Guten Nacht!", "Guten Morgen!", "Hallo!"] },
          { q: "Hogyan mondod: 'A nevem Anna'?", a: ["Ich heiße Anna."], options: ["Ich bin Anna.", "Ich heiße Anna.", "Mein Name ist Anna.", "Ich habe Anna."] },
          { q: "Mit jelent: 'Wie heißt du?'?", a: ["Hogy hívnak?"], options: ["Hogy vagy?", "Mi újság?", "Hogy hívnak?", "Ki vagy?"] },
          { q: "Mit válaszolsz: 'Wie geht es dir?'?", a: ["Gut, danke."], options: ["Hallo!", "Ich heiße...", "Gut, danke.", "Tschüss!"] },
          { q: "Mit jelent: 'Tschüss'?", a: ["Viszlát!"], options: ["Szia!", "Viszlát!", "Kérlek!", "Köszönöm!"] },
          { q: "Mit mondasz, ha este köszönsz el?", a: ["Gute Nacht!"], options: ["Guten Tag!", "Gute Nacht!", "Tschüss!", "Hallo!"] },
          { q: "Mit jelent: 'Freut mich!'", a: ["Örülök!"], options: ["Fáradt vagyok", "Örülök!", "Köszönöm!", "Szívesen!"] },
          { q: "Mit mondasz, ha bemutatkozol?", a: ["Ich heiße..."], options: ["Wie heißt du?", "Ich heiße...", "Guten Tag!", "Hallo!"] },
          { q: "Hogyan köszönsz informálisan?", a: ["Hallo!"], options: ["Guten Tag!", "Hallo!", "Auf Wiedersehen!", "Gute Nacht!"] },
          { q: "Mi a 'Viszontlátásra!' németül?", a: ["Auf Wiedersehen!"], options: ["Tschüss!", "Bis bald!", "Auf Wiedersehen!", "Ciao!"] },
          { q: "Mit mondasz, ha valakit először látsz?", a: ["Freut mich!"], options: ["Hallo!", "Freut mich!", "Tschüss!", "Wie geht’s?"] },
          { q: "Mi a 'Köszönöm' németül?", a: ["Danke"], options: ["Bitte", "Danke", "Hallo", "Tschüss"] },
          { q: "Mit jelent: 'Bitte'?", a: ["Kérem / Szívesen"], options: ["Kérem / Szívesen", "Köszönöm", "Igen", "Nem"] },
          { q: "Mit válaszolsz: 'Danke schön!'?", a: ["Bitte!"], options: ["Danke!", "Bitte!", "Ja!", "Hallo!"] },
          { q: "Hogyan kérdezed: 'Hogy vagy?'?", a: ["Wie geht es dir?"], options: ["Wie geht’s?", "Wie geht es dir?", "Wie bist du?", "Wie heißt du?"] },
          { q: "Mit jelent: 'Ich komme aus Ungarn'?", a: ["Magyarországról jövök."], options: ["Magyarul beszélek.", "Magyarországról jövök.", "Budapesten lakom.", "Éhes vagyok."] },
          { q: "Mit válaszolsz: 'Woher kommst du?'?", a: ["Ich komme aus Ungarn."], options: ["Ich wohne in Berlin.", "Ich komme aus Ungarn.", "Ich bin müde.", "Ich heiße Peter."] },
          { q: "Mit jelent: 'Wie alt bist du?'?", a: ["Hány éves vagy?"], options: ["Milyen magas vagy?", "Hány éves vagy?", "Mi a neved?", "Hol laksz?"] },
          { q: "Mit válaszolsz: 'Wie alt bist du?'?", a: ["Ich bin 14 Jahre alt."], options: ["Ich heiße Peter.", "Ich bin 14 Jahre alt.", "Ich wohne in Szeged.", "Ich komme aus Wien."] },
        ],
      },
      {
        id: "szamok_datum_ido",
        title: "Számok, dátum, idő",
        color: "#7dd3fc",
        questions: [
          { q: "Hogyan mondjuk németül: 21?", a: ["einundzwanzig"], options: ["zwanzigeins", "einundzwanzig", "zwanzigundeins", "einsundzwanzig"] },
          { q: "Mi a helyes alak: 34?", a: ["vierunddreißig"], options: ["dreiundvierzig", "vierunddreizig", "vierunddreißig", "vierzigdrei"] },
          { q: "Melyik a helyes: 100?", a: ["einhundert"], options: ["hundert eins", "einhundert", "hunderten", "eins hundert"] },
          { q: "‘der dritte Mai’ mit jelent?", a: ["május 3."], options: ["május 2.", "május 3.", "május 13.", "május 30."] },
          { q: "Hogyan kérdezed németül: ‘Hány óra van?’", a: ["Wie spät ist es?"], options: ["Wie lange ist es?", "Wie spät ist es?", "Wie viel Uhr ist es?", "Wann ist es?"] },
          { q: "Mit jelent: ‘Es ist halb drei.’", a: ["fél három"], options: ["három óra", "fél három", "fél kettő", "negyed három"] },
          { q: "Mit jelent: ‘Viertel nach acht’?", a: ["8:15"], options: ["7:45", "8:15", "8:45", "8:30"] },
          { q: "Mit jelent: ‘Viertel vor neun’?", a: ["8:45"], options: ["9:15", "8:45", "8:15", "9:45"] },
          { q: "Hogyan mondod: 7:30?", a: ["halb acht"], options: ["halb sieben", "halb acht", "sieben dreißig", "acht halb"] },
          { q: "Hogyan mondod: 10:05?", a: ["fünf nach zehn"], options: ["fünf vor zehn", "zehn fünf", "fünf nach zehn", "zehn und fünf"] },
          { q: "Hogyan mondod: 11:55?", a: ["fünf vor zwölf"], options: ["fünf nach zwölf", "fünf vor zwölf", "elf fünfundfünfzig", "halb zwölf"] },
          { q: "Mit jelent: ‘am 12. Juli’?", a: ["július 12-én"], options: ["július 2-án", "december 7-én", "július 12-én", "július 21-én"] },
          { q: "Melyik a ‘kedd’ németül?", a: ["Dienstag"], options: ["Donnerstag", "Dienstag", "Freitag", "Mittwoch"] },
          { q: "Melyik a ‘szeptember’ németül?", a: ["September"], options: ["Sebtember", "Septembre", "September", "Septembar"] },
          { q: "Hogyan mondod: ‘ma’?", a: ["heute"], options: ["morgen", "gestern", "heute", "übermorgen"] },
          { q: "Hogyan mondod: ‘holnapután’?", a: ["übermorgen"], options: ["übermorgen", "morgenüber", "vorgestern", "nachmorgen"] },
          { q: "Mit jelent: ‘gestern’?", a: ["tegnap"], options: ["ma", "tegnap", "holnap", "mindjárt"] },
          { q: "Mit jelent: ‘nächste Woche’?", a: ["következő hét"], options: ["múlt hét", "ezen a héten", "következő hét", "két hét múlva"] },
          { q: "Melyik a helyes írás: 73?", a: ["dreiundsiebzig"], options: ["siebzigdrei", "siebenunddreißig", "dreisiebzig", "dreiundsiebzig"] },
          { q: "Hogyan mondod: 2000?", a: ["zweitausend"], options: ["zwei Tausend", "zweitausend", "zweihunderttausend", "zweitousend"] },
        ],
      },
    ],
  },

  /* ========== 2) Nyelvtan – igeidők és szerkezetek ========== */
  {
    id: "nemet_grammatika",
    title: "Nyelvtan – igeidők és szerkezetek",
    sections: [
      {
        id: "presens",
        title: "Präsens (jelen idő)",
        color: "#86efac",
        questions: [
          { q: "Mi a 'spielen' (játszani) ige alakja 1. személyben?", a: ["ich spiele"], options: ["ich spielst", "ich spiele", "ich spielt", "ich spielen"] },
          { q: "Mi a 'lernen' (tanulni) alakja 2. személyben?", a: ["du lernst"], options: ["du lernt", "du lernen", "du lernst", "du lerne"] },
          { q: "Mi a 'kommen' (jönni) ige ragozása 'er' esetén?", a: ["er kommt"], options: ["er kommen", "er kommt", "er komme", "er kommst"] },
          { q: "Mi a 'machen' (csinálni) ige 'wir' alakja?", a: ["wir machen"], options: ["wir macht", "wir machen", "wir mache", "wir machst"] },
          { q: "Mi a 'haben' (birtokolni) ige 1. személyű alakja?", a: ["ich habe"], options: ["ich hast", "ich habe", "ich hat", "ich habst"] },
          { q: "Mi a 'sein' ige alakja 3. személyben?", a: ["er ist"], options: ["er bist", "er ist", "er sind", "er sein"] },
          { q: "Mit jelent: 'Ich gehe nach Hause.'", a: ["Hazamegyek."], options: ["Hazaértem.", "Hazamegyek.", "Otthon vagyok.", "Elmegyek otthonról."] },
          { q: "Mi a 'lesen' (olvasni) ige ragozása 'du' esetén?", a: ["du liest"], options: ["du lesen", "du liest", "du lesest", "du list"] },
          { q: "Mit jelent: 'Wir schreiben einen Brief.'", a: ["Levelet írunk."], options: ["Írtunk egy levelet.", "Levelet írunk.", "Levelet írni fogunk.", "Levelet olvasunk."] },
          { q: "Mi a 'sehen' (látni) alakja 'er' esetén?", a: ["er sieht"], options: ["er seht", "er sieht", "er sehen", "er siehtet"] },
          { q: "Melyik a helyes mondat?", a: ["Ich wohne in Szeged."], options: ["Ich wohne in Szeged.", "Ich wohnt in Szeged.", "Ich wohnst in Szeged.", "Ich wohne auf Szeged."] },
          { q: "Hogyan mondod: 'Te olvasol egy könyvet'?", a: ["Du liest ein Buch."], options: ["Du lese ein Buch.", "Du liest ein Buch.", "Du lesen ein Buch.", "Du list ein Buch."] },
          { q: "Mit jelent: 'Er arbeitet in Berlin.'?", a: ["Berlinben dolgozik."], options: ["Berlinben él.", "Berlinbe dolgozik.", "Berlinben dolgozik.", "Berlinből jött."] },
          { q: "Mi a 'trinken' (inni) ige 'ihr' alakja?", a: ["ihr trinkt"], options: ["ihr trinken", "ihr trinkt", "ihr trinket", "ihr trinkst"] },
          { q: "Mit jelent: 'Sie spielen Tennis.'?", a: ["Ők teniszeznek."], options: ["Ők teniszezni fognak.", "Ők teniszeznek.", "Ők teniszeztek.", "Ő teniszezik."] },
          { q: "Mi a 'wohnen' ige jelentése?", a: ["lakni"], options: ["menni", "lakni", "dolgozni", "vásárolni"] },
          { q: "Mi a 'arbeiten' (dolgozni) ige 2. személyben?", a: ["du arbeitest"], options: ["du arbeitet", "du arbeitest", "du arbeiten", "du arbeitst"] },
          { q: "Mit jelent: 'Wir gehen ins Kino.'?", a: ["Moziba megyünk."], options: ["Moziban vagyunk.", "Moziba megyünk.", "Mozit építünk.", "Moziba járunk."] },
          { q: "Melyik az 'Ich bin müde.' fordítása?", a: ["Fáradt vagyok."], options: ["Fáradt voltam.", "Fáradt vagyok.", "Fáradt leszek.", "Fáradt vagy."] },
          { q: "Mi a 'du bist' ige alapformája?", a: ["sein"], options: ["sein", "haben", "gehen", "arbeiten"] },
        ],
      },
      {
        id: "perfekt",
        title: "Perfekt (befejezett múlt)",
        color: "#a7f3d0",
        questions: [
          { q: "Melyik segédigével képezzük általában a Perfektet tranzitív igéknél?", a: ["haben"], options: ["sein", "haben", "werden", "dürfen"] },
          { q: "Melyik ige tipikusan a ‘sein’ segédigét kapja Perfektben?", a: ["gehen"], options: ["lernen", "machen", "gehen", "spielen"] },
          { q: "Mi a 'machen' Partizip II alakja?", a: ["gemacht"], options: ["gemachen", "gemacht", "machen", "gemachtet"] },
          { q: "Mi a 'fahren' Partizip II alakja?", a: ["gefahren"], options: ["gefahrt", "gefahren", "gefahrtet", "gefahrenen"] },
          { q: "Mi a helyes: ‘Ich ___ nach Hause gegangen.’", a: ["bin"], options: ["habe", "bin", "werde", "sein"] },
          { q: "Mi a helyes: ‘Wir ___ viel gelernt.’", a: ["haben"], options: ["sind", "hat", "haben", "seid"] },
          { q: "Válaszd a helyes Perfekt alakot: ‘er / kommen’", a: ["Er ist gekommen."], options: ["Er hat gekommen.", "Er ist gekommen.", "Er hat gekommt.", "Er ist gekommt."] },
          { q: "Válaszd a helyes Perfekt alakot: ‘sie (Pl.) / sehen den Film’", a: ["Sie haben den Film gesehen."], options: ["Sie sind den Film gesehen.", "Sie haben den Film gesehen.", "Sie haben den Film sahen.", "Sie sind den Film sahen."] },
          { q: "Mi a ‘essen’ Partizip II alakja?", a: ["gegessen"], options: ["gegessen", "geessen", "essen", "gegässe"] },
          { q: "Melyik mondat helyes szórendű Perfektben?", a: ["Gestern habe ich Fußball gespielt."], options: ["Gestern ich habe Fußball gespielt.", "Gestern habe ich Fußball gespielt.", "Gestern habe Fußball ich gespielt.", "Gestern ich Fußball habe gespielt."] },
          { q: "Mi a ‘lesen’ (olvasni) Perfekt alakja ‘du’-val?", a: ["Du hast gelesen."], options: ["Du bist gelesen.", "Du hast gelesen.", "Du hast geleset.", "Du bist geleset."] },
          { q: "Mi a ‘sein’ Perfekt alakja ‘wir’-rel?", a: ["Wir sind gewesen."], options: ["Wir haben gewesen.", "Wir sind gewesen.", "Wir sind gewesenet.", "Wir haben gewest."] },
          { q: "Elváló igék: ‘aufstehen’ Perfektben?", a: ["ist aufgestanden"], options: ["hat geaufsteht", "ist aufgestanden", "hat aufgestanden", "ist geaufsteht"] },
          { q: "Válaszd ki, amelyik ‘haben’-nel áll Perfektben:", a: ["spielen"], options: ["fahren", "gehen", "bleiben", "spielen"] },
          { q: "Válaszd ki, amelyik ‘sein’-nel áll Perfektben:", a: ["bleiben"], options: ["lernen", "arbeiten", "bleiben", "machen"] },
          { q: "Mi a ‘schreiben’ Partizip II alakja?", a: ["geschrieben"], options: ["geschriebt", "geschrieben", "geschrebt", "geschreben"] },
          { q: "Tagadás Perfektben: ‘Nem ettem semmit.’", a: ["Ich habe nichts gegessen."], options: ["Ich bin nichts gegessen.", "Ich habe nichts gegessen.", "Ich habe kein gegessen.", "Ich bin kein gegessen."] },
          { q: "Tárgyas mondat Perfektben: ‘Ő (fiú) megitta a teát.’", a: ["Er hat den Tee getrunken."], options: ["Er ist den Tee getrunken.", "Er hat den Tee getrunken.", "Er hat den Tee trinkt.", "Er ist Tee getrunken."] },
          { q: "Kérdés Perfektben: ‘Mikor jöttél haza?’", a: ["Wann bist du nach Hause gekommen?"], options: ["Wann hast du nach Hause gekommen?", "Wann bist du nach Hause gekommen?", "Wann bist du nach Hause gekommt?", "Wann hast du nach Hause gekommt?"] },
          { q: "Helyhatározó + Perfekt: ‘Tegnap Berlinben voltam.’", a: ["Ich bin gestern in Berlin gewesen."], options: ["Ich habe gestern in Berlin gewesen.", "Ich bin gestern in Berlin gewesen.", "Ich bin gestern in Berlin geweset.", "Ich habe gestern in Berlin gewest."] },
        ],
      },
      {
        id: "prateritum",
        title: "Präteritum (elbeszélő múlt)",
        color: "#fde68a",
        questions: [
          { q: "Mit jelent a 'Präteritum'?", a: ["elbeszélő múlt"], options: ["befejezett múlt", "jelen idő", "elbeszélő múlt", "jövő idő"] },
          { q: "Melyik az ige Präteritum alakja: 'sein'?", a: ["war"], options: ["bin", "war", "gewesen", "wäre"] },
          { q: "Melyik az ige Präteritum alakja: 'haben'?", a: ["hatte"], options: ["habe", "hatte", "gehabt", "hättet"] },
          { q: "Mi a 'gehen' Präteritum alakja?", a: ["ging"], options: ["gegangen", "ging", "geht", "gangen"] },
          { q: "Mi a 'kommen' Präteritum alakja?", a: ["kam"], options: ["gekommen", "kam", "kommt", "kommte"] },
          { q: "Mi a 'sehen' Präteritum alakja?", a: ["sah"], options: ["gesehen", "sah", "siehte", "sieht"] },
          { q: "Mi a 'schreiben' Präteritum alakja?", a: ["schrieb"], options: ["geschrieben", "schrieb", "schreibte", "schreibt"] },
          { q: "Mi a 'nehmen' Präteritum alakja?", a: ["nahm"], options: ["genommen", "nahm", "nimmt", "nahmt"] },
          { q: "Mi a 'finden' Präteritum alakja?", a: ["fand"], options: ["gefunden", "fand", "fandet", "finde"] },
          { q: "Mi a 'trinken' Präteritum alakja?", a: ["trank"], options: ["getrunken", "trank", "trinkte", "trinkt"] },
          { q: "Mi a 'sprechen' Präteritum alakja?", a: ["sprach"], options: ["gesprochen", "sprach", "spricht", "sprechte"] },
          { q: "Mi a 'lesen' Präteritum alakja?", a: ["las"], options: ["gelesen", "las", "liest", "lesen"] },
          { q: "Mit jelent: 'Ich war müde.'?", a: ["Fáradt voltam."], options: ["Fáradt vagyok.", "Fáradt voltam.", "Fáradt leszek.", "Fáradt lehetnék."] },
          { q: "Mit jelent: 'Wir hatten keine Zeit.'?", a: ["Nem volt időnk."], options: ["Nincs időnk.", "Volt időnk.", "Nem volt időnk.", "Lesz időnk."] },
          { q: "Mit jelent: 'Er ging nach Hause.'?", a: ["Hazament."], options: ["Hazamegy.", "Hazament.", "Haza fog menni.", "Haza szokott menni."] },
          { q: "Mit jelent: 'Sie kam spät.'?", a: ["Későn jött."], options: ["Későn jön.", "Későn jött.", "Későn fog jönni.", "Mindig jön."] },
          { q: "Mi a 'mögen' Präteritum alakja?", a: ["mochte"], options: ["mag", "möchte", "mochte", "mögen"] },
          { q: "Mi a 'wissen' Präteritum alakja?", a: ["wusste"], options: ["weiß", "wusste", "gewusst", "wüste"] },
          { q: "Mit jelent: 'Ich konnte nicht kommen.'?", a: ["Nem tudtam jönni."], options: ["Nem tudok jönni.", "Nem tudtam jönni.", "Nem jövök.", "Nem akarok jönni."] },
          { q: "Melyik mondat helyes Präteritumban?", a: ["Er arbeitete viel."], options: ["Er arbeitet viel.", "Er arbeitete viel.", "Er hat viel gearbeitet.", "Er arbeitetet viel."] },
        ],
      },
      {
        id: "modalverben",
        title: "Módbeli segédigék",
        color: "#f9a8d4",
        questions: [
          { q: "Mit jelent a 'können'?", a: ["tudni (képesnek lenni)"], options: ["tudni (ismerni)", "tudni (képesnek lenni)", "kelleni", "szeretni"] },
          { q: "Mit jelent a 'müssen'?", a: ["kell"], options: ["akar", "kell", "tud", "engedélyt kap"] },
          { q: "Mit jelent a 'dürfen'?", a: ["szabad (megengedett)"], options: ["tilos", "szeretne", "szabad (megengedett)", "muszáj"] },
          { q: "Mit jelent a 'sollen'?", a: ["kellene, illik"], options: ["akar", "kellene, illik", "tud", "szeret"] },
          { q: "Mit jelent a 'wollen'?", a: ["akarni"], options: ["kelleni", "akarni", "tudni", "kívánni"] },
          { q: "Mit jelent a 'mögen'?", a: ["szeretni (kedvelni)"], options: ["akarni", "tudni", "szeretni (kedvelni)", "kelleni"] },
          { q: "Mi a 'können' alakja 'ich' esetén?", a: ["ich kann"], options: ["ich könne", "ich kann", "ich konnte", "ich kannst"] },
          { q: "Mi a 'müssen' alakja 'du' esetén?", a: ["du musst"], options: ["du müsst", "du musst", "du müss", "du müssen"] },
          { q: "Mi a 'dürfen' alakja 'er' esetén?", a: ["er darf"], options: ["er dürft", "er darf", "er dürfen", "er darfst"] },
          { q: "Mi a 'sollen' alakja 'wir' esetén?", a: ["wir sollen"], options: ["wir sollt", "wir sollen", "wir sollet", "wir sollst"] },
          { q: "Mi a 'wollen' alakja 'ihr' esetén?", a: ["ihr wollt"], options: ["ihr wollen", "ihr wollt", "ihr willt", "ihr wollest"] },
          { q: "Mi a 'mögen' alakja 'sie (Pl.)' esetén?", a: ["sie mögen"], options: ["sie mögen", "sie mag", "sie mögt", "sie mog"] },
          { q: "Mit jelent: 'Ich kann schwimmen.'?", a: ["Tudok úszni."], options: ["Akarok úszni.", "Tudok úszni.", "Úsznom kell.", "Szeretek úszni."] },
          { q: "Mit jelent: 'Du musst lernen.'?", a: ["Tanulnod kell."], options: ["Tanulhatsz.", "Tanulnod kell.", "Tanulsz.", "Szeretsz tanulni."] },
          { q: "Mit jelent: 'Er darf fernsehen.'?", a: ["Nézhet tévét."], options: ["Nézi a tévét.", "Nézhet tévét.", "Kell tévét néznie.", "Nem nézhet tévét."] },
          { q: "Mit jelent: 'Wir sollen helfen.'?", a: ["Segítenünk kell."], options: ["Segíthetünk.", "Segítenünk kell.", "Szeretnénk segíteni.", "Nem segítünk."] },
          { q: "Mit jelent: 'Ich will Arzt werden.'?", a: ["Orvos akarok lenni."], options: ["Orvos vagyok.", "Orvos leszek.", "Orvos akarok lenni.", "Szeretek orvos lenni."] },
          { q: "Mit jelent: 'Ich mag Pizza.'?", a: ["Szeretem a pizzát."], options: ["Kell pizzát ennem.", "Szeretem a pizzát.", "Szeretnék pizzát.", "Eszem pizzát."] },
          { q: "Mi a helyes mondat: 'Mi szeretnénk aludni.'", a: ["Wir möchten schlafen."], options: ["Wir mögen schlafen.", "Wir wollen schlafen.", "Wir möchten schlafen.", "Wir müsst schlafen."] },
          { q: "Melyik mondat helyes: 'Ő nem tud úszni.'", a: ["Er kann nicht schwimmen."], options: ["Er kann nicht schwimmen.", "Er nicht kann schwimmen.", "Er schwimmen kann nicht.", "Er kann schwimmt nicht."] },
        ],
      },
      {
        id: "wortstellung",
        title: "Szórend főmondatban / mellékmondatban",
        color: "#fca5a5",
        questions: [
          { q: "Mi a főmondat alapvető szórendje németül?", a: ["alany – ige – többi rész"], options: ["ige – alany – tárgy", "alany – ige – többi rész", "tárgy – ige – alany", "alany – tárgy – ige"] },
          { q: "Hányadik helyen áll az ige a főmondatban?", a: ["2."], options: ["1.", "2.", "3.", "utolsó"] },
          { q: "Melyik mondat helyes?", a: ["Ich gehe heute ins Kino."], options: ["Ich heute gehe ins Kino.", "Ich gehe heute ins Kino.", "Gehe ich heute ins Kino.", "Ich gehe ins heute Kino."] },
          { q: "Mi történik, ha a mondat elején határozó áll? (pl. Heute)", a: ["Fordított szórend lesz: ige kerül a 2. helyre."], options: ["Nem változik.", "Fordított szórend lesz: ige kerül a 2. helyre.", "Az alany eltűnik.", "A határozó a végére kerül."] },
          { q: "Melyik mondat helyes?", a: ["Heute gehe ich in die Schule."], options: ["Heute ich gehe in die Schule.", "Heute gehe ich in die Schule.", "Ich gehe heute in die Schule.", "Gehe heute ich in die Schule."] },
          { q: "Mi a mellékmondat igehelye?", a: ["a végén"], options: ["az elején", "a második helyen", "a végén", "a harmadik helyen"] },
          { q: "Melyik kötőszó vezet be mellékmondatot?", a: ["weil"], options: ["und", "aber", "weil", "oder"] },
          { q: "Mi a helyes: 'Nem megyek iskolába, mert beteg vagyok.'", a: ["Ich gehe nicht zur Schule, weil ich krank bin."], options: ["Ich gehe nicht zur Schule, weil bin ich krank.", "Ich gehe nicht zur Schule, weil ich krank bin.", "Ich gehe nicht zur Schule, weil ich bin krank.", "Weil ich krank bin, ich gehe nicht zur Schule."] },
          { q: "Mi a helyes: 'Ha esik, otthon maradok.'", a: ["Wenn es regnet, bleibe ich zu Hause."], options: ["Wenn regnet es, bleibe ich zu Hause.", "Wenn es regnet, bleibe ich zu Hause.", "Es regnet, wenn bleibe ich zu Hause.", "Wenn es regnet, ich bleibe zu Hause."] },
          { q: "Mi a helyes szórend kérdésben (W-Frage)?", a: ["Kérdőszó – ige – alany"], options: ["Alany – ige – kérdőszó", "Ige – kérdőszó – alany", "Kérdőszó – ige – alany", "Alany – kérdőszó – ige"] },
          { q: "Mit jelent: 'Warum lernst du Deutsch?'?", a: ["Miért tanulsz németül?"], options: ["Mikor tanulsz németül?", "Miért tanulsz németül?", "Mit tanulsz németül?", "Ki tanul németül?"] },
          { q: "Melyik a helyes főmondat?", a: ["Er liest ein Buch."], options: ["Liest er ein Buch.", "Er liest ein Buch.", "Ein Buch liest er?", "Er ein Buch liest."] },
          { q: "Melyik a helyes mellékmondat?", a: ["..., weil er ein Buch liest."], options: ["..., weil liest er ein Buch.", "..., weil er ein Buch liest.", "..., weil er liest ein Buch.", "..., weil er ein Buch lesen."] },
          { q: "Melyik kötőszó nem okoz szórendváltozást?", a: ["und"], options: ["weil", "dass", "und", "wenn"] },
          { q: "Mit jelent: 'Ich bleibe zu Hause, wenn es kalt ist.'?", a: ["Otthon maradok, ha hideg van."], options: ["Otthon maradok, ha hideg van.", "Otthon voltam, ha hideg van.", "Hideg van, mert otthon maradok.", "Hidegben nem maradok otthon."] },
          { q: "Mi a 'dass' kötőszó jelentése?", a: ["hogy"], options: ["mert", "ha", "amikor", "hogy"] },
          { q: "Melyik mondat helyes 'dass'-szal?", a: ["Ich weiß, dass du recht hast."], options: ["Ich weiß, dass du hast recht.", "Ich weiß, dass du recht hast.", "Ich weiß, du hast dass recht.", "Ich weiß, dass du recht bist."] },
          { q: "Mit jelent: 'Ich glaube, dass er kommt.'?", a: ["Azt hiszem, hogy jön."], options: ["Hiszek benne, hogy elment.", "Azt hiszem, hogy jön.", "Tudom, hogy jött.", "Szeretem, hogy jön."] },
          { q: "Mi a helyes sorrend főmondatban tagadással?", a: ["alany – ige – többi – 'nicht'"], options: ["alany – nicht – ige – tárgy", "alany – ige – többi – 'nicht'", "nicht – alany – ige – tárgy", "ige – alany – 'nicht' – tárgy"] },
          { q: "Melyik mondat helyes: 'Holnap nem megyek dolgozni.'", a: ["Morgen gehe ich nicht zur Arbeit."], options: ["Morgen ich gehe nicht zur Arbeit.", "Morgen gehe ich nicht zur Arbeit.", "Ich gehe morgen zur Arbeit nicht.", "Morgen nicht ich gehe zur Arbeit."] },
        ],
      },
    ],
  },

  /* ========== 3) Szókincs témakörök ========== */
  {
    id: "nemet_szokincs",
    title: "Szókincs témakörök",
    sections: [
      { id: "csalad_es_baratok", title: "Család és barátok", color: "#c7d2fe" },
      { id: "iskola", title: "Iskola, tantárgyak, napirend", color: "#93c5fd" },
      { id: "szabadido_sport", title: "Szabadidő, sport, hobbik", color: "#7dd3fc" },
      { id: "utazas_kozlekedes", title: "Utazás és közlekedés", color: "#60a5fa" },
      { id: "eletmod_egeszseg", title: "Életmód és egészség", color: "#86efac" },
    ],
  },
{
  id: "nemet_szokincs",
  title: "Szókincs témakörök",
  sections: [
    /* ===== 1. Család és barátok ===== */
    {
      id: "csalad_es_baratok",
      title: "Család és barátok",
      color: "#c7d2fe",
      questions: [
        { q: "Mit jelent: 'die Mutter'?", a: ["anya"], options: ["anya", "apa", "nővér", "nagymama"] },
        { q: "Mit jelent: 'der Vater'?", a: ["apa"], options: ["apa", "fiú", "nagypapa", "férj"] },
        { q: "Mit jelent: 'die Geschwister'?", a: ["testvérek"], options: ["szülők", "testvérek", "rokonok", "gyerekek"] },
        { q: "Mit jelent: 'der Bruder'?", a: ["fiútestvér"], options: ["fiútestvér", "nőtestvér", "unokatestvér", "veje"] },
        { q: "Mit jelent: 'die Schwester'?", a: ["lánytestvér"], options: ["lánytestvér", "nő", "feleség", "meny"] },
        { q: "Mit jelent: 'die Großmutter'?", a: ["nagymama"], options: ["keresztanya", "nagymama", "nagynéni", "dédmama"] },
        { q: "Mit jelent: 'der Großvater'?", a: ["nagypapa"], options: ["nagypapa", "após", "nagybácsi", "keresztapa"] },
        { q: "Mit jelent: 'die Eltern'?", a: ["szülők"], options: ["gyerekek", "szülők", "rokonok", "nagyszülők"] },
        { q: "Mit jelent: 'der Onkel'?", a: ["nagybácsi"], options: ["nagybácsi", "sógor", "após", "vő"] },
        { q: "Mit jelent: 'die Tante'?", a: ["nagynéni"], options: ["nagynéni", "meny", "lánytestvér", "keresztanya"] },
        { q: "Mit jelent: 'der Cousin'?", a: ["unokatestvér (fiú)"], options: ["unokatestvér (fiú)", "sógor", "barát", "fiútestvér"] },
        { q: "Mit jelent: 'die Cousine'?", a: ["unokatestvér (lány)"], options: ["unokatestvér (lány)", "meny", "barátnő", "lánytestvér"] },
        { q: "Mit jelent: 'der Freund'?", a: ["barát / fiúbarát"], options: ["férj", "barát / fiúbarát", "ismerős", "osztálytárs"] },
        { q: "Mit jelent: 'die Freundin'?", a: ["barátnő"], options: ["barátnő", "feleség", "lánytestvér", "ismerős"] },
        { q: "Hogyan mondod: 'Ő a bátyám.'?", a: ["Er ist mein Bruder."], options: ["Er ist mein Bruder.", "Er ist meine Schwester.", "Er ist mein Onkel.", "Er ist mein Vater."] },
        { q: "Hogyan mondod: 'Van egy nővérem.'?", a: ["Ich habe eine Schwester."], options: ["Ich habe eine Schwester.", "Ich habe einen Bruder.", "Ich bin eine Schwester.", "Ich habe die Schwester."] },
        { q: "Mit jelent: 'Ich habe zwei Geschwister.'?", a: ["Két testvérem van."], options: ["Két testvérem van.", "Két gyerekem van.", "Két szülőm van.", "Két unokatestvérem van."] },
        { q: "Mit jelent: 'verheiratet'?", a: ["házas"], options: ["házas", "egyedülálló", "elvált", "özvegy"] },
        { q: "Mit jelent: 'ledig'?", a: ["nőtlen/hajadon"], options: ["házas", "nőtlen/hajadon", "elvált", "özvegy"] },
        { q: "Válaszd a helyes mondatot!", a: ["Meine Eltern arbeiten viel."], options: ["Meine Eltern arbeitet viel.", "Meine Eltern arbeiten viel.", "Mein Eltern arbeiten viel.", "Eltern meine arbeiten viel."] },
      ],
    },

    /* ===== 2. Iskola, tantárgyak, napirend ===== */
    {
      id: "iskola",
      title: "Iskola, tantárgyak, napirend",
      color: "#93c5fd",
      questions: [
        { q: "Mit jelent: 'die Schule'?", a: ["iskola"], options: ["iskola", "osztály", "tanóra", "ház"] },
        { q: "Mit jelent: 'der Lehrer'?", a: ["tanár"], options: ["tanár", "tanuló", "igazgató", "szülő"] },
        { q: "Mit jelent: 'die Lehrerin'?", a: ["tanárnő"], options: ["tanárnő", "diáklány", "nővér", "igazgatónő"] },
        { q: "Mit jelent: 'der Schüler'?", a: ["diák (fiú)"], options: ["diák (fiú)", "tanár", "barát", "gyerek"] },
        { q: "Mit jelent: 'die Schülerin'?", a: ["diáklány"], options: ["tanárnő", "diáklány", "barátnő", "unokatestvér"] },
        { q: "Mit jelent: 'das Fach'?", a: ["tantárgy"], options: ["tanóra", "tantárgy", "füzet", "jegyzet"] },
        { q: "Mit jelent: 'die Pause'?", a: ["szünet"], options: ["szünet", "tanóra", "kirándulás", "vizsga"] },
        { q: "Mit jelent: 'die Hausaufgabe'?", a: ["házi feladat"], options: ["házi feladat", "vizsga", "felmérő", "feladatlap"] },
        { q: "Mit jelent: 'das Klassenzimmer'?", a: ["osztályterem"], options: ["tanterem", "folyosó", "osztályterem", "udvar"] },
        { q: "Mit jelent: 'der Stundenplan'?", a: ["órarend"], options: ["órarend", "napló", "füzet", "tanmenet"] },
        { q: "Mit jelent: 'Mathematik'?", a: ["matematika"], options: ["matematika", "fizika", "kémia", "irodalom"] },
        { q: "Mit jelent: 'der Unterricht'?", a: ["tanítás"], options: ["tanítás", "tanár", "tanóra", "tanulás"] },
        { q: "Mit jelent: 'die Note'?", a: ["jegy"], options: ["jegy", "hang", "betű", "szám"] },
        { q: "Mit jelent: 'Ich lerne Deutsch.'?", a: ["Németet tanulok."], options: ["Németül beszélek.", "Németet tanulok.", "Németországban élek.", "Német vagyok."] },
        { q: "Mit jelent: 'Ich gehe in die Schule.'?", a: ["Iskolába megyek."], options: ["Iskolába megyek.", "Iskolában vagyok.", "Iskolába jártam.", "Tanulok otthon."] },
        { q: "Mit jelent: 'die Prüfung'?", a: ["vizsga"], options: ["dolgozat", "vizsga", "órarend", "feladat"] },
        { q: "Mit jelent: 'lernen'?", a: ["tanulni"], options: ["tanulni", "tanítani", "írni", "olvasni"] },
        { q: "Mit jelent: 'schreiben'?", a: ["írni"], options: ["írni", "olvasni", "számolni", "rajzolni"] },
        { q: "Mit jelent: 'lesen'?", a: ["olvasni"], options: ["olvasni", "írni", "beszélni", "hallgatni"] },
        { q: "Mit jelent: 'Ich habe Pause.'?", a: ["Szünetem van."], options: ["Szünetem van.", "Tanórám van.", "Vizsgázom.", "Tanulok."] },
      ],
    },

    /* ===== 3. Szabadidő, sport, hobbik ===== */
    {
      id: "szabadido_sport",
      title: "Szabadidő, sport, hobbik",
      color: "#7dd3fc",
      questions: [
        { q: "Mit jelent: 'der Sport'?", a: ["sport"], options: ["sport", "játék", "kirándulás", "tánc"] },
        { q: "Mit jelent: 'schwimmen'?", a: ["úszni"], options: ["úszni", "futni", "táncolni", "ugrani"] },
        { q: "Mit jelent: 'tanzen'?", a: ["táncolni"], options: ["táncolni", "futni", "énekelni", "rajzolni"] },
        { q: "Mit jelent: 'lesen'?", a: ["olvasni"], options: ["írni", "olvasni", "rajzolni", "festeni"] },
        { q: "Mit jelent: 'Musik hören'?", a: ["zenét hallgatni"], options: ["zenét hallgatni", "zenét írni", "zenét játszani", "zenét venni"] },
        { q: "Mit jelent: 'Fußball spielen'?", a: ["focizni"], options: ["focizni", "kosarazni", "kézilabdázni", "sakkot játszani"] },
        { q: "Mit jelent: 'Rad fahren'?", a: ["biciklizni"], options: ["biciklizni", "vezetni", "sétálni", "ugrani"] },
        { q: "Mit jelent: 'Freunde treffen'?", a: ["barátokkal találkozni"], options: ["barátokkal találkozni", "barátokat írni", "barátokat hívni", "barátokat venni"] },
        { q: "Mit jelent: 'fernsehen'?", a: ["tévét nézni"], options: ["tévét nézni", "tévét venni", "tévét szerelni", "tévét bekapcsolni"] },
        { q: "Mit jelent: 'kochen'?", a: ["főzni"], options: ["főzni", "enni", "vásárolni", "sütni"] },
        { q: "Mit jelent: 'backen'?", a: ["sütni"], options: ["főzni", "sütni", "enni", "inni"] },
        { q: "Mit jelent: 'spielen'?", a: ["játszani"], options: ["játszani", "futni", "rajzolni", "tanulni"] },
        { q: "Mit jelent: 'zeichnen'?", a: ["rajzolni"], options: ["rajzolni", "írni", "futni", "olvasni"] },
        { q: "Mit jelent: 'wandern'?", a: ["túrázni"], options: ["túrázni", "futni", "ugrani", "úszni"] },
        { q: "Mit jelent: 'laufen'?", a: ["futni"], options: ["futni", "sétálni", "úszni", "biciklizni"] },
        { q: "Mit jelent: 'Ich sehe gern Filme.'?", a: ["Szeretek filmeket nézni."], options: ["Szeretek filmeket nézni.", "Filmeket nézek.", "Filmeket veszek.", "Filmeket írok."] },
        { q: "Mit jelent: 'Was machst du in deiner Freizeit?'?", a: ["Mit csinálsz a szabadidődben?"], options: ["Mikor mész dolgozni?", "Mit csinálsz a szabadidődben?", "Kivel sportolsz?", "Hol élsz?"] },
        { q: "Mit jelent: 'Ich gehe oft spazieren.'?", a: ["Gyakran sétálok."], options: ["Gyakran sétálok.", "Sétálni fogok.", "Mindig sétálok.", "Sétáltam."] },
        { q: "Mit jelent: 'Ich spiele Gitarre.'?", a: ["Gitározom."], options: ["Gitározom.", "Zongorázom.", "Dobolok.", "Énekelek."] },
        { q: "Mit jelent: 'Ich habe viele Hobbys.'?", a: ["Sok hobbim van."], options: ["Sok hobbim van.", "Nincs hobbim.", "Egy hobbim van.", "Néha hobbizom."] },
      ],
    },

    /* ===== 4. Utazás és közlekedés ===== */
    {
      id: "utazas_kozlekedes",
      title: "Utazás és közlekedés",
      color: "#60a5fa",
      questions: [
        { q: "Mit jelent: 'reisen'?", a: ["utazni"], options: ["utazni", "repülni", "sétálni", "biciklizni"] },
        { q: "Mit jelent: 'der Zug'?", a: ["vonat"], options: ["vonat", "busz", "repülő", "autó"] },
        { q: "Mit jelent: 'der Bus'?", a: ["busz"], options: ["busz", "villamos", "vonat", "autó"] },
        { q: "Mit jelent: 'das Auto'?", a: ["autó"], options: ["bicikli", "autó", "busz", "vonat"] },
        { q: "Mit jelent: 'das Fahrrad'?", a: ["bicikli"], options: ["bicikli", "motor", "autó", "roller"] },
        { q: "Mit jelent: 'das Flugzeug'?", a: ["repülő"], options: ["repülő", "hajó", "autó", "vonat"] },
        { q: "Mit jelent: 'das Schiff'?", a: ["hajó"], options: ["hajó", "csónak", "repülő", "autó"] },
        { q: "Mit jelent: 'die U-Bahn'?", a: ["metró"], options: ["metró", "vonat", "villamos", "busz"] },
        { q: "Mit jelent: 'die Straße'?", a: ["utca"], options: ["út", "tér", "utca", "állomás"] },
        { q: "Mit jelent: 'die Haltestelle'?", a: ["megálló"], options: ["megálló", "állomás", "pályaudvar", "bejárat"] },
        { q: "Mit jelent: 'der Flughafen'?", a: ["repülőtér"], options: ["repülőtér", "állomás", "hajókikötő", "buszvégállomás"] },
        { q: "Mit jelent: 'das Ticket'?", a: ["jegy"], options: ["jegy", "útlevél", "pénz", "útiterv"] },
        { q: "Mit jelent: 'die Reise'?", a: ["utazás"], options: ["utazás", "kirándulás", "nyaralás", "útlevél"] },
        { q: "Mit jelent: 'der Fahrer'?", a: ["sofőr"], options: ["utas", "sofőr", "ellenőr", "pénztáros"] },
        { q: "Mit jelent: 'der Fahrplan'?", a: ["menetrend"], options: ["menetrend", "térkép", "útlevél", "útvonal"] },
        { q: "Mit jelent: 'der Koffer'?", a: ["bőrönd"], options: ["bőrönd", "táska", "zsák", "hátizsák"] },
        { q: "Mit jelent: 'die Ampel'?", a: ["jelzőlámpa"], options: ["jelzőlámpa", "tábla", "híd", "alagút"] },
        { q: "Mit jelent: 'Ich fahre mit dem Bus.'?", a: ["Busszal utazom."], options: ["Autóval megyek.", "Busszal utazom.", "Vonattal megyek.", "Repülök."] },
                { q: "Mit jelent: 'Ich gehe zu Fuß.'?", a: ["Gyalog megyek."], options: ["Autóval megyek.", "Busszal utazom.", "Gyalog megyek.", "Vonattal utazom."] },
        { q: "Mit jelent: 'Wie komme ich zum Bahnhof?'?", a: ["Hogyan jutok el az állomásra?"], options: ["Hol van az iskola?", "Hogyan jutok el az állomásra?", "Hány óra van?", "Merre van a bolt?"] },
        { q: "Mit jelent: 'Ich fahre nach Wien.'?", a: ["Bécsbe utazom."], options: ["Bécsben vagyok.", "Bécsbe utazom.", "Bécsből jövök.", "Bécsbe repülök."] },
        { q: "Mit jelent: 'Der Zug kommt pünktlich.'?", a: ["A vonat pontosan érkezik."], options: ["A vonat késik.", "A vonat pontosan érkezik.", "A vonat elment.", "A vonat megáll."] },
        { q: "Mit jelent: 'Der Bus ist voll.'?", a: ["A busz tele van."], options: ["A busz üres.", "A busz tele van.", "A busz jön.", "A busz új."] },
      ],
    },

    /* ===== 5. Életmód és egészség ===== */
    {
      id: "eletmod_egeszseg",
      title: "Életmód és egészség",
      color: "#86efac",
      questions: [
        { q: "Mit jelent: 'gesund'?", a: ["egészséges"], options: ["beteg", "egészséges", "fáradt", "éhes"] },
        { q: "Mit jelent: 'krank'?", a: ["beteg"], options: ["egészséges", "beteg", "éhes", "szomjas"] },
        { q: "Mit jelent: 'die Gesundheit'?", a: ["egészség"], options: ["éhség", "egészség", "pihenés", "betegség"] },
        { q: "Mit jelent: 'der Arzt'?", a: ["orvos"], options: ["orvos", "ápoló", "tanár", "beteg"] },
        { q: "Mit jelent: 'die Apotheke'?", a: ["gyógyszertár"], options: ["kórház", "bolt", "gyógyszertár", "iskola"] },
        { q: "Mit jelent: 'die Tablette'?", a: ["tabletta"], options: ["szirup", "tabletta", "kenőcs", "kapszula"] },
        { q: "Mit jelent: 'das Medikament'?", a: ["gyógyszer"], options: ["gyógyszer", "vitamin", "gyümölcs", "ital"] },
        { q: "Mit jelent: 'Ich habe Kopfschmerzen.'?", a: ["Fáj a fejem."], options: ["Fáj a fejem.", "Fáj a hátam.", "Fáj a hasam.", "Fáj a lábam."] },
        { q: "Mit jelent: 'Mir ist schlecht.'?", a: ["Rosszul vagyok."], options: ["Rosszul vagyok.", "Jól vagyok.", "Éhes vagyok.", "Fázom."] },
        { q: "Mit jelent: 'Ich bin müde.'?", a: ["Fáradt vagyok."], options: ["Fáradt vagyok.", "Éhes vagyok.", "Szomjas vagyok.", "Büszke vagyok."] },
        { q: "Mit jelent: 'Ich bin hungrig.'?", a: ["Éhes vagyok."], options: ["Éhes vagyok.", "Szomjas vagyok.", "Beteg vagyok.", "Fázom."] },
        { q: "Mit jelent: 'Ich bin durstig.'?", a: ["Szomjas vagyok."], options: ["Éhes vagyok.", "Fáradt vagyok.", "Szomjas vagyok.", "Beteg vagyok."] },
        { q: "Mit jelent: 'Ich bleibe im Bett.'?", a: ["Ágyban maradok."], options: ["Elmegyek aludni.", "Felkelek.", "Ágyban maradok.", "Elmegyek dolgozni."] },
        { q: "Mit jelent: 'Ich trinke Tee.'?", a: ["Teát iszom."], options: ["Teát főzök.", "Teát iszom.", "Teát veszek.", "Teát adok."] },
        { q: "Mit jelent: 'der Zahnarzt'?", a: ["fogorvos"], options: ["orvos", "fogorvos", "gyógyszerész", "tanár"] },
        { q: "Mit jelent: 'das Krankenhaus'?", a: ["kórház"], options: ["bolt", "kórház", "gyógyszertár", "iskola"] },
        { q: "Mit jelent: 'Ich esse Obst und Gemüse.'?", a: ["Gyümölcsöt és zöldséget eszem."], options: ["Gyümölcsöt és zöldséget eszem.", "Húst és halat eszem.", "Csokit eszem.", "Levest eszem."] },
        { q: "Mit jelent: 'Ich treibe Sport.'?", a: ["Sportolok."], options: ["Sportolok.", "Táncolok.", "Futok.", "Dolgozom."] },
        { q: "Mit jelent: 'Ich schlafe acht Stunden.'?", a: ["Nyolc órát alszom."], options: ["Nyolc órát alszom.", "Nyolc órát dolgozom.", "Nyolc órát futok.", "Nyolc órát tanulok."] },
        { q: "Mit jelent: 'Ich lebe gesund.'?", a: ["Egészségesen élek."], options: ["Egészségesen élek.", "Betegen élek.", "Jól alszom.", "Sokat tanulok."] },
      ],
    },
  ],
},


  /* ========== 4) Kommunikációs helyzetek ========== */
  {
    id: "nemet_kommunikacio",
    title: "Kommunikációs helyzetek",
    sections: [
      { id: "vasarlas_vendeglatas", title: "Vásárlás, vendéglátás", color: "#f9a8d4" },
      { id: "utbaigazitas", title: "Útbaigazítás, segítségkérés", color: "#fde68a" },
      { id: "orvosnal", title: "Orvosnál, gyógyszertárban", color: "#fca5a5" },
      { id: "iskolai_szituaciok", title: "Iskolai szituációk", color: "#c7d2fe" },
    ],
  },
{
  id: "nemet_kommunikacio",
  title: "Kommunikációs helyzetek",
  sections: [
    /* ===== 1) Vásárlás, vendéglátás ===== */
    {
      id: "vasarlas_vendeglatas",
      title: "Vásárlás, vendéglátás",
      color: "#f9a8d4",
      questions: [
        { q: "Mit jelent: 'Ich möchte bezahlen.'?", a: ["Fizetni szeretnék."], options: ["Fizetni szeretnék.", "Enni szeretnék.", "Kérdezni szeretnék.", "Pihenni szeretnék."] },
        { q: "Mit jelent: 'Wie viel kostet das?'?", a: ["Mennyibe kerül ez?"], options: ["Mennyibe kerül ez?", "Hol van ez?", "Mi ez?", "Kinek szól ez?"] },
        { q: "Mit jelent: 'die Rechnung'?", a: ["számla"], options: ["számla", "pénztár", "vásárlás", "pénztárca"] },
        { q: "Mit jelent: 'das Geschäft'?", a: ["bolt"], options: ["bolt", "iroda", "utca", "piac"] },
        { q: "Mit jelent: 'der Supermarkt'?", a: ["áruház"], options: ["áruház", "étterem", "piac", "boltocska"] },
        { q: "Mit jelent: 'die Verkäuferin'?", a: ["eladónő"], options: ["vásárló", "eladónő", "pincérnő", "tanárnő"] },
        { q: "Mit jelent: 'der Kellner'?", a: ["pincér"], options: ["eladó", "pincér", "sofőr", "tanár"] },
        { q: "Mit jelent: 'die Speisekarte'?", a: ["étlap"], options: ["étlap", "számla", "asztal", "szalvéta"] },
        { q: "Mit jelent: 'Ich nehme ein Eis.'?", a: ["Kérek egy fagyit."], options: ["Kérek egy fagyit.", "Főzök egy kávét.", "Eszem egy süteményt.", "Iszom egy teát."] },
        { q: "Mit jelent: 'Ein Wasser, bitte.'?", a: ["Egy vizet, kérem."], options: ["Egy kávét, kérem.", "Egy vizet, kérem.", "Egy sört, kérem.", "Egy teát, kérem."] },
        { q: "Mit jelent: 'Das schmeckt gut.'?", a: ["Ez finom."], options: ["Ez finom.", "Ez drága.", "Ez hideg.", "Ez régi."] },
        { q: "Mit jelent: 'Ich habe Hunger.'?", a: ["Éhes vagyok."], options: ["Éhes vagyok.", "Szomjas vagyok.", "Fáradt vagyok.", "Boldog vagyok."] },
        { q: "Mit jelent: 'Ich bin satt.'?", a: ["Jóllaktam."], options: ["Jóllaktam.", "Éhes vagyok.", "Fázom.", "Alszom."] },
        { q: "Mit jelent: 'Guten Appetit!'?", a: ["Jó étvágyat!"], options: ["Jó étvágyat!", "Egészségedre!", "Viszlát!", "Jó reggelt!"] },
        { q: "Mit jelent: 'Zum Mitnehmen?'?", a: ["Elvitelre?"], options: ["Helyben?", "Elvitelre?", "Útra?", "Most rögtön?"] },
        { q: "Mit jelent: 'Ich zahle bar.'?", a: ["Készpénzzel fizetek."], options: ["Bankkártyával fizetek.", "Készpénzzel fizetek.", "Nem fizetek.", "Utánvéttel fizetek."] },
        { q: "Mit jelent: 'Ich brauche eine Tüte.'?", a: ["Szükségem van egy zacskóra."], options: ["Szükségem van egy zacskóra.", "Kérek egy kanalat.", "El szeretnék menni.", "Kérek egy széket."] },
        { q: "Mit jelent: 'Haben Sie frisches Brot?'?", a: ["Van friss kenyerük?"], options: ["Van friss kenyerük?", "Van kávé?", "Van cukor?", "Van hely?"] },
        { q: "Mit jelent: 'Ich hätte gern ein Stück Kuchen.'?", a: ["Szeretnék egy szelet süteményt."], options: ["Szeretnék egy szelet süteményt.", "Sütök egy tortát.", "Veszek egy kávét.", "Főzök egy levest."] },
        { q: "Mit jelent: 'Danke, das ist alles.'?", a: ["Köszönöm, ez minden."], options: ["Köszönöm, ez minden.", "Nem kérek semmit.", "Ez nagyon finom.", "Ez túl drága."] },
      ],
    },

    /* ===== 2) Útbaigazítás, segítségkérés ===== */
    {
      id: "utbaigazitas",
      title: "Útbaigazítás, segítségkérés",
      color: "#fde68a",
      questions: [
        { q: "Mit jelent: 'Wo ist der Bahnhof?'?", a: ["Hol van az állomás?"], options: ["Hol van az iskola?", "Hol van az állomás?", "Hány óra van?", "Milyen messze van?"] },
        { q: "Mit jelent: 'Entschuldigung, können Sie mir helfen?'?", a: ["Elnézést, tudna segíteni?"], options: ["Elnézést, tudna segíteni?", "Hol lakik?", "Van ideje?", "Siet?"] },
        { q: "Mit jelent: 'geradeaus'?", a: ["egyenesen"], options: ["jobbra", "balra", "egyenesen", "vissza"] },
        { q: "Mit jelent: 'links'?", a: ["balra"], options: ["jobbra", "balra", "előre", "vissza"] },
        { q: "Mit jelent: 'rechts'?", a: ["jobbra"], options: ["jobbra", "balra", "vissza", "át a téren"] },
        { q: "Mit jelent: 'nach links abbiegen'?", a: ["balra fordulni"], options: ["balra fordulni", "jobbra menni", "egyenesen haladni", "visszafordulni"] },
        { q: "Mit jelent: 'die Kreuzung'?", a: ["kereszteződés"], options: ["kereszteződés", "híd", "tér", "megálló"] },
        { q: "Mit jelent: 'die Straße entlanggehen'?", a: ["végigmenni az utcán"], options: ["végigmenni az utcán", "átmenni az utcán", "futni az utcán", "megállni az utcán"] },
        { q: "Mit jelent: 'die Ampel'?", a: ["jelzőlámpa"], options: ["jelzőlámpa", "tábla", "megálló", "átjáró"] },
        { q: "Mit jelent: 'die Brücke'?", a: ["híd"], options: ["híd", "utca", "tér", "állomás"] },
        { q: "Mit jelent: 'Wie komme ich zum Museum?'?", a: ["Hogyan jutok el a múzeumba?"], options: ["Hol van a múzeum?", "Hogyan jutok el a múzeumba?", "Mikor nyit a múzeum?", "Milyen messze van a múzeum?"] },
        { q: "Mit jelent: 'in der Nähe'?", a: ["a közelben"], options: ["messze", "a közelben", "balra", "jobbra"] },
        { q: "Mit jelent: 'der Stadtplan'?", a: ["várostérkép"], options: ["térkép", "útlevél", "jegy", "várostérkép"] },
        { q: "Mit jelent: 'Ich suche die Apotheke.'?", a: ["A gyógyszertárat keresem."], options: ["A gyógyszertárat keresem.", "A boltot keresem.", "A kórházat keresem.", "Az iskolát keresem."] },
        { q: "Mit jelent: 'Das ist weit von hier.'?", a: ["Ez messze van innen."], options: ["Ez messze van innen.", "Ez közel van.", "Ez itt van.", "Ez drága."] },
        { q: "Mit jelent: 'Vielen Dank für Ihre Hilfe.'?", a: ["Köszönöm a segítségét."], options: ["Köszönöm a segítségét.", "Köszönöm a látogatást.", "Köszönöm a meghívást.", "Köszönöm az ételt."] },
        { q: "Mit jelent: 'Ich habe mich verlaufen.'?", a: ["Elvesztem."], options: ["Elvesztem.", "Késtem.", "Megérkeztem.", "Sietek."] },
        { q: "Mit jelent: 'der Weg'?", a: ["út"], options: ["út", "tér", "híd", "megálló"] },
        { q: "Mit jelent: 'das Zentrum'?", a: ["központ"], options: ["központ", "állomás", "városrész", "útkereszteződés"] },
        { q: "Mit jelent: 'Das ist gleich hier.'?", a: ["Ez pont itt van."], options: ["Ez pont itt van.", "Ez messze van.", "Ez közel van.", "Ez drága."] },
      ],
    },

    /* ===== 3) Orvosnál, gyógyszertárban ===== */
    {
      id: "orvosnal",
      title: "Orvosnál, gyógyszertárban",
      color: "#fca5a5",
      questions: [
        { q: "Mit jelent: 'Ich bin krank.'?", a: ["Beteg vagyok."], options: ["Beteg vagyok.", "Fáradt vagyok.", "Éhes vagyok.", "Boldog vagyok."] },
        { q: "Mit jelent: 'Ich habe Fieber.'?", a: ["Lázam van."], options: ["Lázam van.", "Fáj a fejem.", "Köhögök.", "Megfáztam."] },
        { q: "Mit jelent: 'Mir tut der Hals weh.'?", a: ["Fáj a torkom."], options: ["Fáj a torkom.", "Fáj a hátam.", "Fáj a lábam.", "Fáj a kezem."] },
        { q: "Mit jelent: 'Ich brauche ein Medikament.'?", a: ["Gyógyszerre van szükségem."], options: ["Gyógyszerre van szükségem.", "Orvosra van szükségem.", "Pihenésre van szükségem.", "Vizsgálatra megyek."] },
        { q: "Mit jelent: 'Ich huste.'?", a: ["Köhögök."], options: ["Köhögök.", "Tüsszentek.", "Fáj a fejem.", "Náthás vagyok."] },
        { q: "Mit jelent: 'Ich niese.'?", a: ["Tüsszentek."], options: ["Tüsszentek.", "Köhögök.", "Sírok.", "Nevetek."] },
        { q: "Mit jelent: 'Ich habe Kopfschmerzen.'?", a: ["Fáj a fejem."], options: ["Fáj a fejem.", "Fáj a lábam.", "Fáj a fogam.", "Fáj a hasam."] },
        { q: "Mit jelent: 'Ich bin müde.'?", a: ["Fáradt vagyok."], options: ["Fáradt vagyok.", "Szomjas vagyok.", "Beteg vagyok.", "Boldog vagyok."] },
        { q: "Mit jelent: 'Ich habe Husten.'?", a: ["Köhögésem van."], options: ["Köhögésem van.", "Lázam van.", "Torkom fáj.", "Fejfájásom van."] },
        { q: "Mit jelent: 'Ich habe Schnupfen.'?", a: ["Náthás vagyok."], options: ["Náthás vagyok.", "Fáj a torkom.", "Lázam van.", "Köhögök."] },
        { q: "Mit jelent: 'der Arzt'?", a: ["orvos"], options: ["orvos", "ápoló", "tanár", "beteg"] },
        { q: "Mit jelent: 'die Apotheke'?", a: ["gyógyszertár"], options: ["gyógyszertár", "bolt", "kórház", "iskola"] },
        { q: "Mit jelent: 'die Tablette'?", a: ["tabletta"], options: ["tabletta", "por", "kenőcs", "csepp"] },
        { q: "Mit jelent: 'das Rezept'?", a: ["recept (orvosi)"], options: ["recept (orvosi)", "főzési recept", "lista", "jegy"] },
        { q: "Mit jelent: 'die Spritze'?", a: ["injekció"], options: ["injekció", "seb", "gyógyszer", "plaster"] },
        { q: "Mit jelent: 'Ich muss im Bett bleiben.'?", a: ["Ágyban kell maradnom."], options: ["Fel kell kelnem.", "Ágyban kell maradnom.", "El kell mennem.", "Dolgoznom kell."] },
        { q: "Mit jelent: 'Ich gehe zum Arzt.'?", a: ["Orvoshoz megyek."], options: ["Orvoshoz megyek.", "Orvos vagyok.", "Kórházban dolgozom.", "Gyógyszert veszek."] },
        { q: "Mit jelent: 'Gute Besserung!'?", a: ["Jobbulást!"], options: ["Jobbulást!", "Viszlát!", "Sok szerencsét!", "Jó étvágyat!"] },
        { q: "Mit jelent: 'Ich fühle mich schlecht.'?", a: ["Rosszul érzem magam."], options: ["Rosszul érzem magam.", "Jól érzem magam.", "Fáradt vagyok.", "Boldog vagyok."] },
        { q: "Mit jelent: 'Ich habe Zahnschmerzen.'?", a: ["Fáj a fogam."], options: ["Fáj a fogam.", "Fáj a hátam.", "Fáj a fejem.", "Fáj a torkom."] },
      ],
    },

    /* ===== 4) Iskolai szituációk ===== */
    {
      id: "iskolai_szituaciok",
      title: "Iskolai szituációk",
      color: "#c7d2fe",
      questions: [
        { q: "Mit jelent: 'Ich habe die Hausaufgaben gemacht.'?", a: ["Megcsináltam a házi feladatot."], options: ["Megcsináltam a házi feladatot.", "Megtanultam a leckét.", "Kihagytam az órát.", "Elfelejtettem a házit."] },
        { q: "Mit jelent: 'Ich bin zu spät gekommen.'?", a: ["Késtem."], options: ["Késtem.", "Elmentem korán.", "Megérkeztem időben.", "Hiányoztam."] },
        { q: "Mit jelent: 'Ich schreibe eine Klassenarbeit.'?", a: ["Dolgozatot írok."], options: ["Dolgozatot írok.", "Levelet írok.", "Tanulok.", "Olvasok."] },
        { q: "Mit jelent: 'Ich muss leise sein.'?", a: ["Csendben kell lennem."], options: ["Hangosan kell beszélnem.", "Csendben kell lennem.", "Ki kell mennem.", "Felhívnom valakit."] },
        { q: "Mit jelent: 'Ich verstehe die Aufgabe nicht.'?", a: ["Nem értem a feladatot."], options: ["Nem értem a feladatot.", "Nem tetszik a feladat.", "Elfelejtettem a feladatot.", "Megcsináltam a feladatot."] },
        { q: "Mit jelent: 'Kannst du mir helfen?'?", a: ["Tudsz segíteni nekem?"], options: ["Tudsz segíteni nekem?", "Van házid?", "Hova mész?", "Hány óra van?"] },
        { q: "Mit jelent: 'Ich brauche einen Bleistift.'?", a: ["Szükségem van egy ceruzára."], options: ["Szükségem van egy ceruzára.", "Szükségem van egy könyvre.", "Szükségem van egy füzetre.", "Szükségem van egy radírra."] },
        { q: "Mit jelent: 'Darf ich aufs Klo gehen?'?", a: ["Kimehetek a mosdóba?"], options: ["Kimehetek a mosdóba?", "Bejöhetek?", "Elmehetek haza?", "Keletre mehetek?"] },
        { q: "Mit jelent: 'Ich habe meine Hausaufgaben vergessen.'?", a: ["Elfelejtettem a házimat."], options: ["Elfelejtettem a házimat.", "Nem csináltam meg a házit.", "Megcsináltam a házit.", "Nincs házim."] },
        { q: "Mit jelent: 'Ich melde mich.'?", a: ["Jelentkezem."], options: ["Jelentkezem.", "Jelentek valamit.", "Jelek vannak.", "Csengetek."] },
        { q: "Mit jelent: 'Was bedeutet dieses Wort?'?", a: ["Mit jelent ez a szó?"], options: ["Mit jelent ez a szó?", "Hol van ez a szó?", "Hány betű ez a szó?", "Ki írta ezt a szót?"] },
        { q: "Mit jelent: 'Ich habe eine Frage.'?", a: ["Van egy kérdésem."], options: ["Van egy kérdésem.", "Van egy válaszom.", "Kérdeztem valamit.", "Nem értem."] },
        { q: "Mit jelent: 'Wiederholen Sie bitte!'?", a: ["Ismételje meg, kérem!"], options: ["Ismételje meg, kérem!", "Olvassa fel, kérem!", "Írja le, kérem!", "Hallgassa meg, kérem!"] },
        { q: "Mit jelent: 'Sprich bitte langsamer!'?", a: ["Beszélj lassabban, kérlek!"], options: ["Beszélj lassabban, kérlek!", "Beszélj hangosabban!", "Ne beszélj!", "Gyorsabban beszélj!"] },
        { q: "Mit jelent: 'Lies bitte den Text vor!'?", a: ["Olvasd fel a szöveget!"], options: ["Olvasd fel a szöveget!", "Írd le a szöveget!", "Fordítsd le a szöveget!", "Tanuld meg a szöveget!"] },
        { q: "Mit jelent: 'Öffnet das Buch auf Seite 12!'?", a: ["Nyissátok ki a könyvet a 12. oldalon!"], options: ["Nyissátok ki a könyvet a 12. oldalon!", "Csukjátok be a könyvet!", "Olvassátok el a 12. oldalt!", "Lapozzatok a 20. oldalra!"] },
        { q: "Mit jelent: 'Der Unterricht beginnt um acht Uhr.'?", a: ["A tanítás 8-kor kezdődik."], options: ["A tanítás 8-kor kezdődik.", "A tanóra 8-kor ér véget.", "A tanítás 7-kor kezdődik.", "A szünet 8-kor kezdődik."] },
        { q: "Mit jelent: 'Wir machen eine Gruppenarbeit.'?", a: ["Csoportmunkát csinálunk."], options: ["Csoportmunkát csinálunk.", "Dolgozatot írunk.", "Szabadidő van.", "Kirándulunk."] },
        { q: "Mit jelent: 'Ich bekomme eine Note.'?", a: ["Jegyet kapok."], options: ["Jegyet kapok.", "Beírást kapok.", "Igazolást kapok.", "Dicséretet kapok."] },
        { q: "Mit jelent: 'Die Stunde ist zu Ende.'?", a: ["Vége az órának."], options: ["Vége az órának.", "Kezdődik az óra.", "Szünet van.", "Vége a napnak."] },
      ],
    },
  ],
},

  /* ========== 5) Landeskunde – D-A-CH ========== */
  {
    id: "nemet_landskunde",
    title: "Landeskunde – D-A-CH",
    sections: [
      { id: "deutschland", title: "Németország – tartományok, városok", color: "#7dd3fc" },
      { id: "osterreich", title: "Ausztria – tartományok és kultúra", color: "#93c5fd" },
      { id: "schweiz", title: "Svájc – kantonok és nyelvek", color: "#60a5fa" },
    ],
  },
{
  id: "nemet_landskunde",
  title: "Landeskunde – D-A-CH",
  sections: [
    /* ===== 1) Németország – tartományok, városok ===== */
    {
      id: "deutschland",
      title: "Németország – tartományok, városok",
      color: "#7dd3fc",
      questions: [
        { q: "Mi Németország fővárosa?", a: ["Berlin"], options: ["Berlin", "München", "Hamburg", "Köln"] },
        { q: "Hány szövetségi tartománya (Bundesländer) van Németországnak?", a: ["16"], options: ["12", "14", "16", "18"] },
        { q: "Melyik NEM városállam Németországban?", a: ["Leipzig"], options: ["Berlin", "Bremen", "Hamburg", "Leipzig"] },
        { q: "Melyik tartományban van München?", a: ["Bayern"], options: ["Bayern", "Sachsen", "Hessen", "NRW"] },
        { q: "Melyik folyó folyik Kölnön keresztül?", a: ["Rajna (Rhein)"], options: ["Duna (Donau)", "Majna (Main)", "Rajna (Rhein)", "Weser"] },
        { q: "Melyik város híres az Oktoberfest-ről?", a: ["München"], options: ["München", "Berlin", "Dresden", "Stuttgart"] },
        { q: "Hol található a Brandenburger Tor?", a: ["Berlin"], options: ["Berlin", "Potsdam", "Bonn", "Frankfurt am Main"] },
        { q: "Melyik autógyártó központja Wolfsburg?", a: ["Volkswagen"], options: ["BMW", "Volkswagen", "Mercedes-Benz", "Porsche"] },
        { q: "Melyik hegyvonulat húzódik Dél-Németországban?", a: ["Az Alpok"], options: ["Harz", "Eifel", "Az Alpok", "Erzgebirge"] },
        { q: "Melyik város pénzügyi központ, az Európai Központi Bank székhelye?", a: ["Frankfurt am Main"], options: ["Frankfurt am Main", "Düsseldorf", "Hannover", "Nürnberg"] },
        { q: "Melyik tenger mossa Németország északi partjait?", a: ["Északi-tenger és Balti-tenger"], options: ["Csak Északi-tenger", "Csak Balti-tenger", "Adriai-tenger", "Északi-tenger és Balti-tenger"] },
        { q: "Melyik város híres a Dómjáról (katedrális)?", a: ["Köln"], options: ["Köln", "Bremen", "Lübeck", "Augsburg"] },
        { q: "Melyik tartomány fővárosa Stuttgart?", a: ["Baden-Württemberg"], options: ["Bayern", "Baden-Württemberg", "Hessen", "Saarland"] },
        { q: "Melyik német város ismert Elbphilharmonie hangversenyterméről?", a: ["Hamburg"], options: ["Hamburg", "Leipzig", "Dresden", "Bonn"] },
        { q: "Melyik városhoz kötődik a karnevál (Rosenmontag) nagy hagyománya?", a: ["Köln"], options: ["Köln", "München", "Berlin", "Rostock"] },
        { q: "Melyik folyó szeli ketté Drezdát?", a: ["Elba"], options: ["Elba", "Weser", "Majna", "Rajna"] },
        { q: "Hol található a Neuschwanstein kastélyhoz legközelebbi város?", a: ["Füssen"], options: ["Füssen", "Ulm", "Regensburg", "Passau"] },
        { q: "Melyik város volt Nyugat-Németország fővárosa 1949–1990 között?", a: ["Bonn"], options: ["Bonn", "Frankfurt", "Hamburg", "Hannover"] },
        { q: "Melyik város a 'zöld' vásárváros (Messestadt), könyvvásárral híres?", a: ["Leipzig"], options: ["Leipzig", "Erfurt", "Kassel", "Dortmund"] },
        { q: "Melyik tartományban található a Fekete-erdő (Schwarzwald)?", a: ["Baden-Württemberg"], options: ["Bayern", "Baden-Württemberg", "Hessen", "Thüringen"] },
      ],
    },

    /* ===== 2) Ausztria – tartományok és kultúra ===== */
    {
      id: "osterreich",
      title: "Ausztria – tartományok és kultúra",
      color: "#93c5fd",
      questions: [
        { q: "Mi Ausztria fővárosa?", a: ["Wien"], options: ["Wien", "Graz", "Linz", "Salzburg"] },
        { q: "Hány tartománya (Bundesländer) van Ausztriának?", a: ["9"], options: ["7", "8", "9", "10"] },
        { q: "Melyik Ausztria legnagyobb folyója?", a: ["Duna (Donau)"], options: ["Inn", "Duna (Donau)", "Mur", "Enns"] },
        { q: "Melyik város híres Mozarttal kapcsolatban?", a: ["Salzburg"], options: ["Salzburg", "Graz", "Innsbruck", "Klagenfurt"] },
        { q: "Melyik városban rendeztek többször téli olimpiát?", a: ["Innsbruck"], options: ["Innsbruck", "Linz", "Bregenz", "Eisenstadt"] },
        { q: "Melyik tartomány fővárosa Graz?", a: ["Steiermark"], options: ["Vorarlberg", "Tirol", "Steiermark", "Burgenland"] },
        { q: "Melyik osztrák desszert híres baracklekvárral töltve?", a: ["Sacher-torte"], options: ["Sacher-torte", "Apfelstrudel", "Topfenstrudel", "Kaiserschmarrn"] },
        { q: "Mi a 'Heuriger'?", a: ["borozó/újboros hely"], options: ["borozó/újboros hely", "hegyi menedékház", "néptánc", "sífelvonó"] },
        { q: "Melyik tó partján rendezik a híres vízi színpadot (Seebühne)?", a: ["Bodeni-tó (Bregenz)"], options: ["Bodeni-tó (Bregenz)", "Wörthersee", "Neusiedler See", "Mondsee"] },
        { q: "Melyik hegység húzódik Ausztria nagy részén?", a: ["Alpok"], options: ["Kárpátok", "Alpok", "Harz", "Dinaridák"] },
        { q: "Melyik épület áll Bécsben? (opera)", a: ["Staatsoper"], options: ["Staatsoper", "Semperoper", "Elbphilharmonie", "Gasteig"] },
        { q: "Melyik tartomány határos Magyarországgal?", a: ["Burgenland"], options: ["Vorarlberg", "Tirol", "Salzburg", "Burgenland"] },
        { q: "Melyik bécsi nevezetesség az uralkodói nyári rezidencia?", a: ["Schönbrunn"], options: ["Schönbrunn", "Belvedere", "Hofburg", "Karlskirche"] },
        { q: "Mi az 'Apfelstrudel'?", a: ["almás rétes"], options: ["almás rétes", "túrós gombóc", "palacsinta", "fánk"] },
        { q: "Melyik városon halad át a Duna Bécs mellett Ausztriában?", a: ["Linz"], options: ["Linz", "Graz", "Klagenfurt", "Innsbruck"] },
        { q: "Melyik folyó folyik Salzburgnál?", a: ["Salzach"], options: ["Inn", "Traun", "Salzach", "Mur"] },
        { q: "Mit jelent a 'Tirol' sokaknak?", a: ["síelés és hegyek"], options: ["síelés és hegyek", "borvidék", "alföld", "tengerpart"] },
        { q: "Melyik osztrák város híres karácsonyi vásáráról (Christkindlmarkt)?", a: ["Wien"], options: ["Wien", "Graz", "Linz", "Eisenstadt"] },
        { q: "Mit találsz a Ringstraße mentén Bécsben?", a: ["reprezentatív középületeket"], options: ["reprezentatív középületeket", "csak lakóházakat", "ipari parkot", "kikötőt"] },
        { q: "Melyik osztrák tartomány nyugati szélén fekszik, svájci határnál?", a: ["Vorarlberg"], options: ["Vorarlberg", "Tirol", "Salzburg", "Kärnten"] },
      ],
    },

    /* ===== 3) Svájc – kantonok és nyelvek ===== */
    {
      id: "schweiz",
      title: "Svájc – kantonok és nyelvek",
      color: "#60a5fa",
      questions: [
        { q: "Mi Svájc fővárosa (szövetségi város)?", a: ["Bern"], options: ["Bern", "Zürich", "Genf", "Basel"] },
        { q: "Hány hivatalos nyelve van Svájcnak?", a: ["4"], options: ["2", "3", "4", "5"] },
        { q: "Melyek Svájc hivatalos nyelvei?", a: ["német, francia, olasz, rétoromán"], options: ["német, francia, olasz, rétoromán", "német, francia, angol, olasz", "francia, olasz, rétoromán, angol", "német, angol, olasz, rétoromán"] },
        { q: "Melyik a legnépesebb svájci város?", a: ["Zürich"], options: ["Zürich", "Genf", "Basel", "Lausanne"] },
        { q: "Melyik nemzetközi szervezet széke Genfben található?", a: ["ENSZ/WHO irodák"], options: ["ENSZ/WHO irodák", "EU Bizottság", "NATO", "Afrikai Unió"] },
        { q: "Melyik hegység uralja Svájc nagy részét?", a: ["Alpok"], options: ["Pireneusok", "Alpok", "Appenninek", "Kárpátok"] },
        { q: "Melyik híres hegycsúcs áll Zermatt mellett?", a: ["Matterhorn"], options: ["Matterhorn", "Mont Blanc", "Zugspitze", "Grossglockner"] },
        { q: "Mi Svájc pénzneme?", a: ["svájci frank (CHF)"], options: ["euró (EUR)", "svájci frank (CHF)", "korona (SEK)", "dollár (USD)"] },
        { q: "Melyik város híres óragyártásáról és a Jet d’Eau szökőkútról?", a: ["Genf"], options: ["Genf", "Bern", "Basel", "Lugano"] },
        { q: "Melyik tavon fekszik Lugano?", a: ["Luganói-tó"], options: ["Genfi-tó", "Bodeni-tó", "Luganói-tó", "Vierwaldstättersee"] },
        { q: "Melyik város ad otthont a svájci parlamentnek (Bundeshaus)?", a: ["Bern"], options: ["Bern", "Zürich", "Lausanne", "St. Gallen"] },
        { q: "Melyik város híres karneváljáról (Fasnacht) Svájcban?", a: ["Basel"], options: ["Basel", "Genf", "Zürich", "Luzern"] },
        { q: "Melyik nyelv dominál Svájc északi és középső részén?", a: ["német"], options: ["német", "francia", "olasz", "rétoromán"] },
        { q: "Melyik kanton olasz nyelvű főként?", a: ["Ticino"], options: ["Ticino", "Graubünden", "Bern", "Vaud"] },
        { q: "Melyik tó partján fekszik Zürich?", a: ["Zürichi-tó"], options: ["Zürichi-tó", "Genfi-tó", "Bodeni-tó", "Bielersee"] },
        { q: "Melyik város a farmervásárokról és a Kapellbrückéről híres?", a: ["Luzern"], options: ["Luzern", "Zürich", "Bern", "Chur"] },
        { q: "Melyik kanton hegyi vasútjai (Jungfraubahn) népszerűek?", a: ["Bern / Valais (Berner Oberland)"], options: ["Bern / Valais (Berner Oberland)", "Zürich", "Ticino", "Aargau"] },
        { q: "Melyik városban található a Nemzetközi Vöröskereszt Múzeuma?", a: ["Genf"], options: ["Genf", "Zürich", "Basel", "Lausanne"] },
        { q: "Melyik város híres svájci csokoládéjáról (Maison Cailler közelében)?", a: ["Broc / Fribourg"], options: ["Broc / Fribourg", "Chur", "Sion", "Neuchâtel"] },
        { q: "Melyik város a CERN közelében fekszik?", a: ["Genf"], options: ["Genf", "Lausanne", "Basel", "Zürich"] },
      ],
    },
  ],
}
];
export default TOPIC_TREE;
